-- V100: Exercices Lecon 3 - Strategy Pattern

-- =============================================
-- EXERCICE 1 : DiscountCalculator avec lambdas (EASY)
-- =============================================

INSERT INTO exercises (lesson_id, title, difficulty, description, starter_code, solution_code, test_code, hints, xp_reward, order_index)
SELECT l.id,
    'DiscountCalculator avec Lambdas',
    'EASY',
    'Creez l interface fonctionnelle DiscountStrategy avec une seule methode double apply(double price). Implementez la classe PriceCalculator avec un champ DiscountStrategy discount initialise par constructeur et une methode calculate(double price) qui retourne discount.apply(price). Dans le main, creez trois calculateurs avec des lambdas : noDiscount (retourne price), tenPercent (retourne price * 0.90), flatFive (retourne price - 5.0). Affichez le resultat de calculate(100.0) pour chacun.',
    E'// TODO: @FunctionalInterface DiscountStrategy\n// double apply(double price)\n\n// TODO: class PriceCalculator\n// - DiscountStrategy discount (initialise par constructeur)\n// - double calculate(double price) : retourne discount.apply(price)\n\npublic class Main {\n    public static void main(String[] args) {\n        PriceCalculator noDiscount   = new PriceCalculator(price -> price);\n        PriceCalculator tenPercent   = new PriceCalculator(price -> price * 0.90);\n        PriceCalculator flatFive     = new PriceCalculator(price -> price - 5.0);\n\n        System.out.println(noDiscount.calculate(100.0));\n        System.out.println(tenPercent.calculate(100.0));\n        System.out.println(flatFive.calculate(100.0));\n    }\n}',
    E'@FunctionalInterface\ninterface DiscountStrategy {\n    double apply(double price);\n}\n\nclass PriceCalculator {\n    private DiscountStrategy discount;\n\n    public PriceCalculator(DiscountStrategy discount) {\n        this.discount = discount;\n    }\n\n    public double calculate(double price) {\n        return discount.apply(price);\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        PriceCalculator noDiscount   = new PriceCalculator(price -> price);\n        PriceCalculator tenPercent   = new PriceCalculator(price -> price * 0.90);\n        PriceCalculator flatFive     = new PriceCalculator(price -> price - 5.0);\n\n        System.out.println(noDiscount.calculate(100.0));\n        System.out.println(tenPercent.calculate(100.0));\n        System.out.println(flatFive.calculate(100.0));\n    }\n}',
    'output.contains("100.0") && output.contains("90.0") && output.contains("95.0")',
    '["@FunctionalInterface garantit que DiscountStrategy n a qu une seule methode abstraite, ce qui permet d ecrire price -> price comme implementation", "PriceCalculator.calculate() appelle simplement discount.apply(price) et retourne le resultat", "Les trois lambdas sont des implementations inline de DiscountStrategy : noDiscount retourne price tel quel, tenPercent applique -10%, flatFive soustrait 5"]',
    30,
    1
FROM lessons l WHERE l.slug = 'strategy-pattern';

-- =============================================
-- EXERCICE 2 : Systeme de paiement (MEDIUM)
-- =============================================

INSERT INTO exercises (lesson_id, title, difficulty, description, starter_code, solution_code, test_code, hints, xp_reward, order_index)
SELECT l.id,
    'ShoppingCart - Modes de Paiement',
    'MEDIUM',
    'Implementez l interface PaymentStrategy avec void pay(double amount). Creez trois strategies concretes : CreditCardPayment(String cardNumber) affiche "Carte " + cardNumber + " : " + amount + " EUR", PaypalPayment(String email) affiche "PayPal " + email + " : " + amount + " EUR", CryptoPayment affiche "Crypto : " + amount + " EUR". Implementez ShoppingCart avec setPaymentStrategy(PaymentStrategy s) et checkout(double amount) qui appelle pay(). Dans le main, effectuez trois paiements : carte "1234-5678" pour 59.99, PayPal "alice@mail.com" pour 25.00, puis Crypto pour 10.50.',
    E'// TODO: interface PaymentStrategy\n// void pay(double amount)\n\n// TODO: class CreditCardPayment implements PaymentStrategy\n// CreditCardPayment(String cardNumber)\n// pay -> "Carte " + cardNumber + " : " + amount + " EUR"\n\n// TODO: class PaypalPayment implements PaymentStrategy\n// PaypalPayment(String email)\n// pay -> "PayPal " + email + " : " + amount + " EUR"\n\n// TODO: class CryptoPayment implements PaymentStrategy\n// pay -> "Crypto : " + amount + " EUR"\n\n// TODO: class ShoppingCart\n// - setPaymentStrategy(PaymentStrategy s)\n// - checkout(double amount) : appelle pay()\n\npublic class Main {\n    public static void main(String[] args) {\n        ShoppingCart cart = new ShoppingCart();\n\n        cart.setPaymentStrategy(new CreditCardPayment("1234-5678"));\n        cart.checkout(59.99);\n\n        cart.setPaymentStrategy(new PaypalPayment("alice@mail.com"));\n        cart.checkout(25.00);\n\n        cart.setPaymentStrategy(new CryptoPayment());\n        cart.checkout(10.50);\n    }\n}',
    E'interface PaymentStrategy {\n    void pay(double amount);\n}\n\nclass CreditCardPayment implements PaymentStrategy {\n    private String cardNumber;\n\n    public CreditCardPayment(String cardNumber) {\n        this.cardNumber = cardNumber;\n    }\n\n    public void pay(double amount) {\n        System.out.println("Carte " + cardNumber + " : " + amount + " EUR");\n    }\n}\n\nclass PaypalPayment implements PaymentStrategy {\n    private String email;\n\n    public PaypalPayment(String email) {\n        this.email = email;\n    }\n\n    public void pay(double amount) {\n        System.out.println("PayPal " + email + " : " + amount + " EUR");\n    }\n}\n\nclass CryptoPayment implements PaymentStrategy {\n    public void pay(double amount) {\n        System.out.println("Crypto : " + amount + " EUR");\n    }\n}\n\nclass ShoppingCart {\n    private PaymentStrategy paymentStrategy;\n\n    public void setPaymentStrategy(PaymentStrategy s) {\n        this.paymentStrategy = s;\n    }\n\n    public void checkout(double amount) {\n        paymentStrategy.pay(amount);\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        ShoppingCart cart = new ShoppingCart();\n\n        cart.setPaymentStrategy(new CreditCardPayment("1234-5678"));\n        cart.checkout(59.99);\n\n        cart.setPaymentStrategy(new PaypalPayment("alice@mail.com"));\n        cart.checkout(25.00);\n\n        cart.setPaymentStrategy(new CryptoPayment());\n        cart.checkout(10.50);\n    }\n}',
    'output.contains("Carte 1234-5678 : 59.99 EUR") && output.contains("PayPal alice@mail.com : 25.0 EUR") && output.contains("Crypto : 10.5 EUR")',
    '["ShoppingCart ne connait que PaymentStrategy, pas les classes concretes : setPaymentStrategy() remplace la strategie en cours", "checkout() appelle simplement paymentStrategy.pay(amount) : c est le patron Strategy en action, le Context delegue a la strategie", "Les trois classes implementent pay(double amount) differemment, mais ShoppingCart les utilise toutes de la meme facon via l interface"]',
    40,
    2
FROM lessons l WHERE l.slug = 'strategy-pattern';

-- =============================================
-- EXERCICE 3 : TextFormatter multi-strategies (HARD)
-- =============================================

INSERT INTO exercises (lesson_id, title, difficulty, description, starter_code, solution_code, test_code, hints, xp_reward, order_index)
SELECT l.id,
    'TextFormatter - Formatage Multi-Strategies',
    'HARD',
    'Implementez l interface TextStrategy avec String format(String text). Creez quatre strategies : UpperCaseStrategy retourne text.toUpperCase(), LowerCaseStrategy retourne text.toLowerCase(), TitleCaseStrategy met la premiere lettre de chaque mot en majuscule (split par espace), ReverseStrategy retourne le texte inverse caractere par caractere. Implementez TextFormatter avec setStrategy(TextStrategy s), apply(String text) qui retourne la transformation, et applyAll(String text, TextStrategy... strategies) qui chaine les transformations (chaque resultat devient l entree suivante). Dans le main, testez chaque strategie et une chaine upper puis reverse sur "hello world".',
    E'// TODO: interface TextStrategy\n// String format(String text)\n\n// TODO: class UpperCaseStrategy implements TextStrategy\n// format -> text.toUpperCase()\n\n// TODO: class LowerCaseStrategy implements TextStrategy\n// format -> text.toLowerCase()\n\n// TODO: class TitleCaseStrategy implements TextStrategy\n// format -> premiere lettre de chaque mot en majuscule\n// Indice : split(" "), capitalize chaque mot, rejoindre avec " "\n\n// TODO: class ReverseStrategy implements TextStrategy\n// format -> texte inverse caractere par caractere\n// Indice : new StringBuilder(text).reverse().toString()\n\n// TODO: class TextFormatter\n// - setStrategy(TextStrategy s)\n// - String apply(String text) : retourne strategy.format(text)\n// - String applyAll(String text, TextStrategy... strategies)\n//   chaine les transformations : resultat de l une devient input de la suivante\n\npublic class Main {\n    public static void main(String[] args) {\n        TextFormatter fmt = new TextFormatter();\n\n        fmt.setStrategy(new UpperCaseStrategy());\n        System.out.println(fmt.apply("hello world"));\n\n        fmt.setStrategy(new LowerCaseStrategy());\n        System.out.println(fmt.apply("BONJOUR JAVA"));\n\n        fmt.setStrategy(new TitleCaseStrategy());\n        System.out.println(fmt.apply("strategy pattern en java"));\n\n        fmt.setStrategy(new ReverseStrategy());\n        System.out.println(fmt.apply("java"));\n\n        // Chaine : upper puis reverse\n        System.out.println(fmt.applyAll("hello", new UpperCaseStrategy(), new ReverseStrategy()));\n    }\n}',
    E'interface TextStrategy {\n    String format(String text);\n}\n\nclass UpperCaseStrategy implements TextStrategy {\n    public String format(String text) {\n        return text.toUpperCase();\n    }\n}\n\nclass LowerCaseStrategy implements TextStrategy {\n    public String format(String text) {\n        return text.toLowerCase();\n    }\n}\n\nclass TitleCaseStrategy implements TextStrategy {\n    public String format(String text) {\n        String[] words = text.split(" ");\n        StringBuilder result = new StringBuilder();\n        for (int i = 0; i < words.length; i++) {\n            if (words[i].length() > 0) {\n                result.append(Character.toUpperCase(words[i].charAt(0)));\n                result.append(words[i].substring(1).toLowerCase());\n            }\n            if (i < words.length - 1) result.append(" ");\n        }\n        return result.toString();\n    }\n}\n\nclass ReverseStrategy implements TextStrategy {\n    public String format(String text) {\n        return new StringBuilder(text).reverse().toString();\n    }\n}\n\nclass TextFormatter {\n    private TextStrategy strategy;\n\n    public void setStrategy(TextStrategy s) {\n        this.strategy = s;\n    }\n\n    public String apply(String text) {\n        return strategy.format(text);\n    }\n\n    public String applyAll(String text, TextStrategy... strategies) {\n        String result = text;\n        for (TextStrategy s : strategies) {\n            result = s.format(result);\n        }\n        return result;\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        TextFormatter fmt = new TextFormatter();\n\n        fmt.setStrategy(new UpperCaseStrategy());\n        System.out.println(fmt.apply("hello world"));\n\n        fmt.setStrategy(new LowerCaseStrategy());\n        System.out.println(fmt.apply("BONJOUR JAVA"));\n\n        fmt.setStrategy(new TitleCaseStrategy());\n        System.out.println(fmt.apply("strategy pattern en java"));\n\n        fmt.setStrategy(new ReverseStrategy());\n        System.out.println(fmt.apply("java"));\n\n        System.out.println(fmt.applyAll("hello", new UpperCaseStrategy(), new ReverseStrategy()));\n    }\n}',
    'output.contains("HELLO WORLD") && output.contains("bonjour java") && output.contains("Strategy Pattern En Java") && output.contains("avaj") && output.contains("OLLEH")',
    '["TitleCaseStrategy : split le texte par espaces, puis pour chaque mot Character.toUpperCase(mot.charAt(0)) + mot.substring(1).toLowerCase()", "ReverseStrategy : new StringBuilder(text).reverse().toString() est la facon idiomatique d inverser une String en Java", "applyAll() avec varargs TextStrategy... : iterez sur le tableau, chaque etape transforme le resultat precedent : result = s.format(result)"]',
    50,
    3
FROM lessons l WHERE l.slug = 'strategy-pattern';
