-- V102: Exercices Lecon 4 - Builder Pattern

-- =============================================
-- EXERCICE 1 : Pizza Builder (EASY)
-- =============================================

INSERT INTO exercises (lesson_id, title, difficulty, description, starter_code, solution_code, test_code, hints, xp_reward, order_index)
SELECT l.id,
    'Pizza Builder',
    'EASY',
    'Implementez la classe Pizza avec les champs String taille, String sauce, boolean olives, boolean jambon. Le constructeur de Pizza doit etre prive et prendre un Builder. Implementez la classe interne statique Pizza.Builder avec : constructeur Builder(String taille), methodes sauce(String s), olives(boolean b), jambon(boolean b) qui retournent this, et build() qui cree la Pizza. Les valeurs par defaut du Builder : sauce = "tomate", olives = false, jambon = false. toString() de Pizza retourne "Pizza " + taille + " | sauce: " + sauce + " | olives: " + olives + " | jambon: " + jambon.',
    E'// TODO: class Pizza\n// - private final String taille, sauce\n// - private final boolean olives, jambon\n// - constructeur prive Pizza(Builder b)\n// - toString() retourne "Pizza " + taille + " | sauce: " + sauce + " | olives: " + olives + " | jambon: " + jambon\n\n// TODO: static class Builder (interne a Pizza)\n// - Builder(String taille) : taille obligatoire\n// - sauce par defaut "tomate", olives false, jambon false\n// - sauce(String s), olives(boolean b), jambon(boolean b) -> retournent this\n// - build() -> new Pizza(this)\n\npublic class Main {\n    public static void main(String[] args) {\n        Pizza p1 = new Pizza.Builder("grande")\n            .sauce("pesto")\n            .olives(true)\n            .build();\n\n        Pizza p2 = new Pizza.Builder("petite")\n            .jambon(true)\n            .build();\n\n        System.out.println(p1);\n        System.out.println(p2);\n    }\n}',
    E'class Pizza {\n    private final String taille;\n    private final String sauce;\n    private final boolean olives;\n    private final boolean jambon;\n\n    private Pizza(Builder b) {\n        this.taille = b.taille;\n        this.sauce  = b.sauce;\n        this.olives = b.olives;\n        this.jambon = b.jambon;\n    }\n\n    public String toString() {\n        return "Pizza " + taille + " | sauce: " + sauce + " | olives: " + olives + " | jambon: " + jambon;\n    }\n\n    public static class Builder {\n        private String taille;\n        private String sauce = "tomate";\n        private boolean olives = false;\n        private boolean jambon = false;\n\n        public Builder(String taille) {\n            this.taille = taille;\n        }\n\n        public Builder sauce(String sauce) {\n            this.sauce = sauce;\n            return this;\n        }\n\n        public Builder olives(boolean olives) {\n            this.olives = olives;\n            return this;\n        }\n\n        public Builder jambon(boolean jambon) {\n            this.jambon = jambon;\n            return this;\n        }\n\n        public Pizza build() {\n            return new Pizza(this);\n        }\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Pizza p1 = new Pizza.Builder("grande")\n            .sauce("pesto")\n            .olives(true)\n            .build();\n\n        Pizza p2 = new Pizza.Builder("petite")\n            .jambon(true)\n            .build();\n\n        System.out.println(p1);\n        System.out.println(p2);\n    }\n}',
    'output.contains("Pizza grande | sauce: pesto | olives: true | jambon: false") && output.contains("Pizza petite | sauce: tomate | olives: false | jambon: true")',
    '["Le constructeur de Pizza est private et prend un Builder : private Pizza(Builder b). Le Builder interne accede a ses champs directement : this.taille = b.taille", "Chaque methode du Builder retourne this (pas void) pour permettre le chaining : public Builder sauce(String s) { this.sauce = s; return this; }", "Les valeurs par defaut sont initialisees dans le Builder : sauce = tomate, olives = false, jambon = false. p2 n appelle pas sauce() donc conserve la valeur par defaut"]',
    30,
    1
FROM lessons l WHERE l.slug = 'builder-pattern';

-- =============================================
-- EXERCICE 2 : Computer Builder avec validation (MEDIUM)
-- =============================================

INSERT INTO exercises (lesson_id, title, difficulty, description, starter_code, solution_code, test_code, hints, xp_reward, order_index)
SELECT l.id,
    'Computer Builder - Configuration PC',
    'MEDIUM',
    'Implementez la classe Computer avec les champs String cpu, int ramGb, int storageGb, boolean ssd, String gpu. Constructeur prive prenant un Builder. toString() retourne cpu + " | RAM: " + ramGb + "GB | Stockage: " + storageGb + "GB " + (ssd ? "SSD" : "HDD") + (gpu != null ? " | GPU: " + gpu : ""). Implementez Computer.Builder : cpu et ramGb obligatoires (dans le constructeur Builder), storageGb par defaut 256, ssd par defaut true, gpu par defaut null. Ajoutez dans build() une validation : si ramGb <= 0 lancer IllegalStateException("RAM invalide"), si storageGb <= 0 lancer IllegalStateException("Stockage invalide"). Construisez 2 ordinateurs differents dans le main.',
    E'// TODO: class Computer\n// - private final String cpu; int ramGb, storageGb; boolean ssd; String gpu\n// - constructeur prive Computer(Builder b)\n// - toString() : cpu + " | RAM: " + ramGb + "GB | Stockage: " + storageGb + "GB " +\n//                (ssd ? "SSD" : "HDD") + (gpu != null ? " | GPU: " + gpu : "")\n\n// TODO: static class Builder\n// - Builder(String cpu, int ramGb) : obligatoires\n// - storageGb(int gb), ssd(boolean b), gpu(String g) -> retournent this\n// - Defauts : storageGb = 256, ssd = true, gpu = null\n// - build() : valide ramGb > 0 et storageGb > 0, sinon IllegalStateException\n\npublic class Main {\n    public static void main(String[] args) {\n        Computer pc1 = new Computer.Builder("Intel i9", 32)\n            .storageGb(1000)\n            .gpu("RTX 4090")\n            .build();\n\n        Computer pc2 = new Computer.Builder("AMD Ryzen 5", 16)\n            .ssd(false)\n            .storageGb(500)\n            .build();\n\n        System.out.println(pc1);\n        System.out.println(pc2);\n\n        try {\n            Computer invalid = new Computer.Builder("CPU", -4).build();\n        } catch (IllegalStateException e) {\n            System.out.println("Erreur: " + e.getMessage());\n        }\n    }\n}',
    E'class Computer {\n    private final String cpu;\n    private final int ramGb;\n    private final int storageGb;\n    private final boolean ssd;\n    private final String gpu;\n\n    private Computer(Builder b) {\n        this.cpu       = b.cpu;\n        this.ramGb     = b.ramGb;\n        this.storageGb = b.storageGb;\n        this.ssd       = b.ssd;\n        this.gpu       = b.gpu;\n    }\n\n    public String toString() {\n        return cpu + " | RAM: " + ramGb + "GB | Stockage: " + storageGb + "GB " +\n            (ssd ? "SSD" : "HDD") +\n            (gpu != null ? " | GPU: " + gpu : "");\n    }\n\n    public static class Builder {\n        private final String cpu;\n        private final int ramGb;\n        private int storageGb = 256;\n        private boolean ssd = true;\n        private String gpu = null;\n\n        public Builder(String cpu, int ramGb) {\n            this.cpu   = cpu;\n            this.ramGb = ramGb;\n        }\n\n        public Builder storageGb(int storageGb) {\n            this.storageGb = storageGb;\n            return this;\n        }\n\n        public Builder ssd(boolean ssd) {\n            this.ssd = ssd;\n            return this;\n        }\n\n        public Builder gpu(String gpu) {\n            this.gpu = gpu;\n            return this;\n        }\n\n        public Computer build() {\n            if (ramGb <= 0) throw new IllegalStateException("RAM invalide");\n            if (storageGb <= 0) throw new IllegalStateException("Stockage invalide");\n            return new Computer(this);\n        }\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Computer pc1 = new Computer.Builder("Intel i9", 32)\n            .storageGb(1000)\n            .gpu("RTX 4090")\n            .build();\n\n        Computer pc2 = new Computer.Builder("AMD Ryzen 5", 16)\n            .ssd(false)\n            .storageGb(500)\n            .build();\n\n        System.out.println(pc1);\n        System.out.println(pc2);\n\n        try {\n            Computer invalid = new Computer.Builder("CPU", -4).build();\n        } catch (IllegalStateException e) {\n            System.out.println("Erreur: " + e.getMessage());\n        }\n    }\n}',
    'output.contains("Intel i9 | RAM: 32GB | Stockage: 1000GB SSD | GPU: RTX 4090") && output.contains("AMD Ryzen 5 | RAM: 16GB | Stockage: 500GB HDD") && output.contains("Erreur: RAM invalide")',
    '["Builder(String cpu, int ramGb) : les parametres obligatoires sont dans le constructeur du Builder. On peut les declarer final dans le Builder", "build() lance IllegalStateException avant de creer l objet : if (ramGb <= 0) throw new IllegalStateException(\"RAM invalide\")", "toString() utilise des expressions ternaires : (ssd ? \"SSD\" : \"HDD\") et (gpu != null ? \" | GPU: \" + gpu : \"\") pour l affichage conditionnel"]',
    40,
    2
FROM lessons l WHERE l.slug = 'builder-pattern';

-- =============================================
-- EXERCICE 3 : QueryBuilder SQL (HARD)
-- =============================================

INSERT INTO exercises (lesson_id, title, difficulty, description, starter_code, solution_code, test_code, hints, xp_reward, order_index)
SELECT l.id,
    'QueryBuilder - Constructeur de Requetes SQL',
    'HARD',
    'Implementez un QueryBuilder fluent pour construire des requetes SQL SELECT. La classe QueryBuilder doit avoir : from(String table) qui definit la table, select(String... columns) qui definit les colonnes (JOIN avec ", "), where(String condition) qui ajoute une condition WHERE (plusieurs appels : "AND " entre conditions), orderBy(String column) et limit(int n). La methode build() retourne la requete SQL sous forme de String construite ainsi : "SELECT " + colonnes + " FROM " + table, puis si where: " WHERE " + conditions jointes par " AND ", puis si orderBy: " ORDER BY " + colonne, puis si limit > 0: " LIMIT " + n. Toutes les methodes retournent this sauf build(). Construisez 3 requetes differentes dans le main.',
    E'// TODO: class QueryBuilder\n// - String table, String[] columns, List<String> conditions, String orderByCol, int limitVal\n// - from(String table) -> this\n// - select(String... columns) -> this\n// - where(String condition) -> this (peut etre appele plusieurs fois)\n// - orderBy(String column) -> this\n// - limit(int n) -> this\n// - String build() : construit et retourne la requete SQL\n//   Format : "SELECT col1, col2 FROM table WHERE cond1 AND cond2 ORDER BY col LIMIT n"\n//   Si select() non appele : colonnes = "*"\n//   WHERE uniquement si au moins une condition\n//   ORDER BY uniquement si orderBy() appele\n//   LIMIT uniquement si limit > 0\n\nimport java.util.ArrayList;\nimport java.util.List;\n\npublic class Main {\n    public static void main(String[] args) {\n        // Requete 1 : simple\n        String q1 = new QueryBuilder()\n            .from("users")\n            .select("id", "name", "email")\n            .where("age > 18")\n            .orderBy("name")\n            .limit(10)\n            .build();\n        System.out.println(q1);\n\n        // Requete 2 : plusieurs conditions\n        String q2 = new QueryBuilder()\n            .from("orders")\n            .select("id", "total")\n            .where("status = \'active\'")\n            .where("total > 100")\n            .build();\n        System.out.println(q2);\n\n        // Requete 3 : select * sans filtre\n        String q3 = new QueryBuilder()\n            .from("products")\n            .limit(5)\n            .build();\n        System.out.println(q3);\n    }\n}',
    E'import java.util.ArrayList;\nimport java.util.List;\nimport java.util.Arrays;\n\nclass QueryBuilder {\n    private String table;\n    private String[] columns;\n    private List<String> conditions = new ArrayList<>();\n    private String orderByCol;\n    private int limitVal = 0;\n\n    public QueryBuilder from(String table) {\n        this.table = table;\n        return this;\n    }\n\n    public QueryBuilder select(String... columns) {\n        this.columns = columns;\n        return this;\n    }\n\n    public QueryBuilder where(String condition) {\n        this.conditions.add(condition);\n        return this;\n    }\n\n    public QueryBuilder orderBy(String column) {\n        this.orderByCol = column;\n        return this;\n    }\n\n    public QueryBuilder limit(int n) {\n        this.limitVal = n;\n        return this;\n    }\n\n    public String build() {\n        StringBuilder sb = new StringBuilder();\n\n        String cols = (columns != null && columns.length > 0)\n            ? String.join(", ", columns)\n            : "*";\n        sb.append("SELECT ").append(cols).append(" FROM ").append(table);\n\n        if (!conditions.isEmpty()) {\n            sb.append(" WHERE ").append(String.join(" AND ", conditions));\n        }\n\n        if (orderByCol != null) {\n            sb.append(" ORDER BY ").append(orderByCol);\n        }\n\n        if (limitVal > 0) {\n            sb.append(" LIMIT ").append(limitVal);\n        }\n\n        return sb.toString();\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        String q1 = new QueryBuilder()\n            .from("users")\n            .select("id", "name", "email")\n            .where("age > 18")\n            .orderBy("name")\n            .limit(10)\n            .build();\n        System.out.println(q1);\n\n        String q2 = new QueryBuilder()\n            .from("orders")\n            .select("id", "total")\n            .where("status = \'active\'")\n            .where("total > 100")\n            .build();\n        System.out.println(q2);\n\n        String q3 = new QueryBuilder()\n            .from("products")\n            .limit(5)\n            .build();\n        System.out.println(q3);\n    }\n}',
    'output.contains("SELECT id, name, email FROM users WHERE age > 18 ORDER BY name LIMIT 10") && output.contains("SELECT id, total FROM orders WHERE status =") && output.contains("AND total > 100") && output.contains("SELECT * FROM products LIMIT 5")',
    '["where() peut etre appele plusieurs fois : chaque appel ajoute a la List<String> conditions. Dans build(), String.join(\" AND \", conditions) les concatene", "select(String... columns) utilise des varargs. String.join(\", \", columns) assemble les colonnes. Si columns est null ou vide, utiliser \"*\"", "build() construit incrementalement avec StringBuilder : ajoutez WHERE/ORDER BY/LIMIT uniquement si les donnees sont presentes (conditions non vide, orderByCol non null, limitVal > 0)"]',
    50,
    3
FROM lessons l WHERE l.slug = 'builder-pattern';
