-- V18: Exercices pratiques POO - Classes et Objets

-- =============================================
-- EXERCICE 1 : Classe Personne (EASY)
-- =============================================

INSERT INTO exercises (lesson_id, title, description, starter_code, solution_code, test_code, hints, difficulty, xp_reward, order_index)
SELECT l.id,
    'Classe Personne',
    'Completez la classe Personne : le constructeur doit initialiser les attributs nom et age avec this, et la methode sePresenter() doit retourner la chaine "Bonjour, je m appelle " + nom + " et j ai " + age + " ans."',
    E'public class Main {\n\n    static class Personne {\n        String nom;\n        int age;\n\n        Personne(String nom, int age) {\n            // TODO: initialisez this.nom et this.age\n        }\n\n        String sePresenter() {\n            // TODO: retournez la phrase de presentation\n            return "";\n        }\n    }\n\n    public static void main(String[] args) {\n        Personne p1 = new Personne("Alice", 25);\n        Personne p2 = new Personne("Bob", 30);\n        System.out.println(p1.sePresenter());\n        System.out.println(p2.sePresenter());\n    }\n}',
    E'public class Main {\n\n    static class Personne {\n        String nom;\n        int age;\n\n        Personne(String nom, int age) {\n            this.nom = nom;\n            this.age = age;\n        }\n\n        String sePresenter() {\n            return "Bonjour, je m appelle " + nom + " et j ai " + age + " ans.";\n        }\n    }\n\n    public static void main(String[] args) {\n        Personne p1 = new Personne("Alice", 25);\n        Personne p2 = new Personne("Bob", 30);\n        System.out.println(p1.sePresenter());\n        System.out.println(p2.sePresenter());\n    }\n}',
    'output.contains("Alice") && output.contains("25") && output.contains("Bob") && output.contains("30")',
    E'Dans le constructeur : this.nom designe l attribut de l objet, nom (sans this) designe le parametre. Ecrivez this.nom = nom et this.age = age. Dans sePresenter() : concatenez avec + en retournant "Bonjour, je m appelle " + nom + " et j ai " + age + " ans."',
    'EASY', 50, 1
FROM lessons l WHERE l.slug = 'classes-et-objets';

-- =============================================
-- EXERCICE 2 : Compte Bancaire (MEDIUM)
-- =============================================

INSERT INTO exercises (lesson_id, title, description, starter_code, solution_code, test_code, hints, difficulty, xp_reward, order_index)
SELECT l.id,
    'Compte Bancaire',
    'Implementez la classe CompteBancaire avec encapsulation : getSolde() retourne le solde prive, deposer(montant) ajoute au solde si montant > 0, retirer(montant) deduit du solde si montant > 0 et montant <= solde (retourne true) sinon ne fait rien (retourne false).',
    E'public class Main {\n\n    static class CompteBancaire {\n        private double solde;\n        private String titulaire;\n\n        CompteBancaire(String titulaire, double soldeInitial) {\n            this.titulaire = titulaire;\n            this.solde = soldeInitial;\n        }\n\n        public double getSolde() {\n            // TODO: retournez le solde\n            return 0;\n        }\n\n        public void deposer(double montant) {\n            // TODO: ajoutez montant au solde si montant > 0\n        }\n\n        public boolean retirer(double montant) {\n            // TODO: retirez montant si possible, retournez true/false\n            return false;\n        }\n    }\n\n    public static void main(String[] args) {\n        CompteBancaire compte = new CompteBancaire("Marie", 500.0);\n        compte.deposer(200.0);\n        System.out.println(compte.getSolde()); // 700.0\n        compte.retirer(150.0);\n        System.out.println(compte.getSolde()); // 550.0\n        boolean ok = compte.retirer(1000.0);\n        System.out.println(ok);               // false\n        System.out.println(compte.getSolde()); // 550.0\n    }\n}',
    E'public class Main {\n\n    static class CompteBancaire {\n        private double solde;\n        private String titulaire;\n\n        CompteBancaire(String titulaire, double soldeInitial) {\n            this.titulaire = titulaire;\n            this.solde = soldeInitial;\n        }\n\n        public double getSolde() {\n            return solde;\n        }\n\n        public void deposer(double montant) {\n            if (montant > 0) {\n                solde += montant;\n            }\n        }\n\n        public boolean retirer(double montant) {\n            if (montant > 0 && montant <= solde) {\n                solde -= montant;\n                return true;\n            }\n            return false;\n        }\n    }\n\n    public static void main(String[] args) {\n        CompteBancaire compte = new CompteBancaire("Marie", 500.0);\n        compte.deposer(200.0);\n        System.out.println(compte.getSolde()); // 700.0\n        compte.retirer(150.0);\n        System.out.println(compte.getSolde()); // 550.0\n        boolean ok = compte.retirer(1000.0);\n        System.out.println(ok);               // false\n        System.out.println(compte.getSolde()); // 550.0\n    }\n}',
    'output.contains("700.0") && output.contains("550.0") && output.contains("false")',
    E'getSolde() : retournez simplement solde. deposer() : verifiez if (montant > 0) puis faites solde += montant. retirer() : verifiez if (montant > 0 && montant <= solde), si oui faites solde -= montant et retournez true. Sinon retournez false. 500 + 200 = 700, 700 - 150 = 550, 1000 > 550 donc retrait refuse.',
    'MEDIUM', 75, 2
FROM lessons l WHERE l.slug = 'classes-et-objets';

-- =============================================
-- EXERCICE 3 : Gestion de livres (HARD)
-- =============================================

INSERT INTO exercises (lesson_id, title, description, starter_code, solution_code, test_code, hints, difficulty, xp_reward, order_index)
SELECT l.id,
    'Gestion de livres',
    'Completez la classe Livre avec encapsulation : isDisponible() retourne l etat prive disponible, emprunter() marque le livre comme non disponible (seulement si disponible), rendre() le remet a disponible, toString() retourne titre + " par " + auteur + " (" + prix + " euros)".',
    E'public class Main {\n\n    static class Livre {\n        private String titre;\n        private String auteur;\n        private double prix;\n        private boolean disponible;\n\n        Livre(String titre, String auteur, double prix) {\n            this.titre = titre;\n            this.auteur = auteur;\n            this.prix = prix;\n            this.disponible = true;\n        }\n\n        public boolean isDisponible() {\n            // TODO: retournez l etat disponible\n            return false;\n        }\n\n        public void emprunter() {\n            // TODO: si disponible, marquez-le comme non disponible\n        }\n\n        public void rendre() {\n            // TODO: remettez le livre a disponible\n        }\n\n        @Override\n        public String toString() {\n            // TODO: retournez titre + " par " + auteur + " (" + prix + " euros)"\n            return "";\n        }\n    }\n\n    public static void main(String[] args) {\n        Livre livre1 = new Livre("Le Petit Prince", "Saint-Exupery", 12.99);\n        System.out.println(livre1);\n        System.out.println(livre1.isDisponible()); // true\n        livre1.emprunter();\n        System.out.println(livre1.isDisponible()); // false\n        livre1.rendre();\n        System.out.println(livre1.isDisponible()); // true\n\n        Livre livre2 = new Livre("Java pour les nuls", "Barry Burd", 29.95);\n        System.out.println(livre2);\n    }\n}',
    E'public class Main {\n\n    static class Livre {\n        private String titre;\n        private String auteur;\n        private double prix;\n        private boolean disponible;\n\n        Livre(String titre, String auteur, double prix) {\n            this.titre = titre;\n            this.auteur = auteur;\n            this.prix = prix;\n            this.disponible = true;\n        }\n\n        public boolean isDisponible() {\n            return disponible;\n        }\n\n        public void emprunter() {\n            if (disponible) {\n                disponible = false;\n            }\n        }\n\n        public void rendre() {\n            disponible = true;\n        }\n\n        @Override\n        public String toString() {\n            return titre + " par " + auteur + " (" + prix + " euros)";\n        }\n    }\n\n    public static void main(String[] args) {\n        Livre livre1 = new Livre("Le Petit Prince", "Saint-Exupery", 12.99);\n        System.out.println(livre1);\n        System.out.println(livre1.isDisponible()); // true\n        livre1.emprunter();\n        System.out.println(livre1.isDisponible()); // false\n        livre1.rendre();\n        System.out.println(livre1.isDisponible()); // true\n\n        Livre livre2 = new Livre("Java pour les nuls", "Barry Burd", 29.95);\n        System.out.println(livre2);\n    }\n}',
    'output.contains("Le Petit Prince") && output.contains("12.99") && output.contains("false") && output.contains("Java pour les nuls")',
    E'isDisponible() : retournez simplement disponible. emprunter() : if (disponible) { disponible = false; }. rendre() : disponible = true; (pas besoin de condition). toString() : retournez titre + " par " + auteur + " (" + prix + " euros)". Le constructeur initialise disponible = true, donc un livre neuf est toujours disponible.',
    'HARD', 100, 3
FROM lessons l WHERE l.slug = 'classes-et-objets';
