-- V22: Exercices Classes Abstraites et Interfaces (lecon 3 POO)

-- =============================================
-- EXERCICE 1 : Formes Geometriques (EASY)
-- =============================================

INSERT INTO exercises (lesson_id, title, description, starter_code, solution_code, test_code, hints, difficulty, xp_reward, order_index)
SELECT l.id,
    'Formes Geometriques',
    'Completez les methodes aire() dans Carre et Cercle. Carre.aire() doit retourner cote * cote. Cercle.aire() doit retourner 3.14 * rayon * rayon. La classe abstraite Forme impose que chaque sous-classe implemente obligatoirement aire(), et sa methode afficher() appelle aire() pour afficher le resultat.',
    E'public class Main {\n\n    abstract static class Forme {\n        String couleur;\n\n        Forme(String couleur) {\n            this.couleur = couleur;\n        }\n\n        abstract double aire();\n\n        void afficher() {\n            System.out.println(couleur + " - aire : " + aire());\n        }\n    }\n\n    static class Carre extends Forme {\n        double cote;\n\n        Carre(double cote, String couleur) {\n            super(couleur);\n            this.cote = cote;\n        }\n\n        @Override\n        double aire() {\n            // TODO: retournez cote * cote\n            return 0;\n        }\n    }\n\n    static class Cercle extends Forme {\n        double rayon;\n\n        Cercle(double rayon, String couleur) {\n            super(couleur);\n            this.rayon = rayon;\n        }\n\n        @Override\n        double aire() {\n            // TODO: retournez 3.14 * rayon * rayon\n            return 0;\n        }\n    }\n\n    public static void main(String[] args) {\n        Forme f1 = new Carre(4, "rouge");\n        Forme f2 = new Cercle(3, "bleu");\n\n        f1.afficher(); // rouge - aire : 16.0\n        f2.afficher(); // bleu - aire : 28.26\n    }\n}',
    E'public class Main {\n\n    abstract static class Forme {\n        String couleur;\n\n        Forme(String couleur) {\n            this.couleur = couleur;\n        }\n\n        abstract double aire();\n\n        void afficher() {\n            System.out.println(couleur + " - aire : " + aire());\n        }\n    }\n\n    static class Carre extends Forme {\n        double cote;\n\n        Carre(double cote, String couleur) {\n            super(couleur);\n            this.cote = cote;\n        }\n\n        @Override\n        double aire() {\n            return cote * cote;\n        }\n    }\n\n    static class Cercle extends Forme {\n        double rayon;\n\n        Cercle(double rayon, String couleur) {\n            super(couleur);\n            this.rayon = rayon;\n        }\n\n        @Override\n        double aire() {\n            return 3.14 * rayon * rayon;\n        }\n    }\n\n    public static void main(String[] args) {\n        Forme f1 = new Carre(4, "rouge");\n        Forme f2 = new Cercle(3, "bleu");\n\n        f1.afficher();\n        f2.afficher();\n    }\n}',
    'output.contains("16.0") && output.contains("rouge") && output.contains("bleu") && output.contains("28")',
    E'Carre.aire() : retournez simplement cote * cote. Pour cote = 4, le resultat est 16.0. Cercle.aire() : retournez 3.14 * rayon * rayon. Pour rayon = 3, le resultat est environ 28.26. La methode afficher() dans la classe abstraite Forme appelle aire() et affichera automatiquement le bon resultat grace au polymorphisme. Chaque sous-classe doit implementer aire() car elle est declaree abstract dans Forme.',
    'EASY', 50, 1
FROM lessons l WHERE l.slug = 'classes-abstraites-interfaces';

-- =============================================
-- EXERCICE 2 : Catalogue Media (MEDIUM)
-- =============================================

INSERT INTO exercises (lesson_id, title, description, starter_code, solution_code, test_code, hints, difficulty, xp_reward, order_index)
SELECT l.id,
    'Catalogue Media',
    'Completez la methode decrire() dans Livre et Film. Livre.decrire() doit retourner "Livre : " + titre + " par " + auteur. Film.decrire() doit retourner "Film : " + titre + " (" + annee + ")". Le tableau Describable[] montre comment une interface permet de traiter uniformement des objets de types differents.',
    E'public class Main {\n\n    interface Describable {\n        String decrire();\n    }\n\n    static class Livre implements Describable {\n        String titre;\n        String auteur;\n\n        Livre(String titre, String auteur) {\n            this.titre = titre;\n            this.auteur = auteur;\n        }\n\n        @Override\n        public String decrire() {\n            // TODO: retournez "Livre : " + titre + " par " + auteur\n            return "";\n        }\n    }\n\n    static class Film implements Describable {\n        String titre;\n        int annee;\n\n        Film(String titre, int annee) {\n            this.titre = titre;\n            this.annee = annee;\n        }\n\n        @Override\n        public String decrire() {\n            // TODO: retournez "Film : " + titre + " (" + annee + ")"\n            return "";\n        }\n    }\n\n    public static void main(String[] args) {\n        Describable[] catalogue = {\n            new Livre("Harry Potter", "J.K. Rowling"),\n            new Film("Avatar", 2009),\n            new Livre("Le Petit Prince", "Antoine de Saint-Exupery"),\n            new Film("Inception", 2010)\n        };\n\n        for (Describable item : catalogue) {\n            System.out.println(item.decrire());\n        }\n    }\n}',
    E'public class Main {\n\n    interface Describable {\n        String decrire();\n    }\n\n    static class Livre implements Describable {\n        String titre;\n        String auteur;\n\n        Livre(String titre, String auteur) {\n            this.titre = titre;\n            this.auteur = auteur;\n        }\n\n        @Override\n        public String decrire() {\n            return "Livre : " + titre + " par " + auteur;\n        }\n    }\n\n    static class Film implements Describable {\n        String titre;\n        int annee;\n\n        Film(String titre, int annee) {\n            this.titre = titre;\n            this.annee = annee;\n        }\n\n        @Override\n        public String decrire() {\n            return "Film : " + titre + " (" + annee + ")";\n        }\n    }\n\n    public static void main(String[] args) {\n        Describable[] catalogue = {\n            new Livre("Harry Potter", "J.K. Rowling"),\n            new Film("Avatar", 2009),\n            new Livre("Le Petit Prince", "Antoine de Saint-Exupery"),\n            new Film("Inception", 2010)\n        };\n\n        for (Describable item : catalogue) {\n            System.out.println(item.decrire());\n        }\n    }\n}',
    'output.contains("Harry Potter") && output.contains("J.K. Rowling") && output.contains("Avatar") && output.contains("2009") && output.contains("Inception")',
    E'Livre.decrire() : retournez "Livre : " + titre + " par " + auteur. Le resultat pour "Harry Potter" de "J.K. Rowling" sera : "Livre : Harry Potter par J.K. Rowling". Film.decrire() : retournez "Film : " + titre + " (" + annee + ")". Pour Avatar 2009 : "Film : Avatar (2009)". Le polymorphisme via l interface Describable permet d appeler decrire() sur chaque element du tableau sans savoir si c est un Livre ou un Film : Java choisit automatiquement la bonne version.',
    'MEDIUM', 75, 2
FROM lessons l WHERE l.slug = 'classes-abstraites-interfaces';

-- =============================================
-- EXERCICE 3 : Vehicules et Interface Rechargeable (HARD)
-- =============================================

INSERT INTO exercises (lesson_id, title, description, starter_code, solution_code, test_code, hints, difficulty, xp_reward, order_index)
SELECT l.id,
    'Vehicules et Interface Rechargeable',
    'Completez VoitureElectrique : le constructeur doit appeler super(marque), vitesseMax() retourne 150.0, autonomie() retourne autonomieKm. Completez Moto : vitesseMax() retourne 200.0. La boucle utilise instanceof pour detecter les vehicules rechargeables et afficher leur autonomie.',
    E'public class Main {\n\n    abstract static class Vehicule {\n        String marque;\n\n        Vehicule(String marque) {\n            this.marque = marque;\n        }\n\n        abstract double vitesseMax();\n\n        void afficher() {\n            System.out.println(marque + " - vitesse max : " + vitesseMax() + " km/h");\n        }\n    }\n\n    interface Rechargeable {\n        int autonomie();\n    }\n\n    static class VoitureElectrique extends Vehicule implements Rechargeable {\n        int autonomieKm;\n\n        VoitureElectrique(String marque, int autonomieKm) {\n            // TODO: appelez super(marque) et initialisez autonomieKm\n            this.autonomieKm = autonomieKm;\n        }\n\n        @Override\n        double vitesseMax() {\n            // TODO: retournez 150.0\n            return 0;\n        }\n\n        @Override\n        public int autonomie() {\n            // TODO: retournez autonomieKm\n            return 0;\n        }\n    }\n\n    static class Moto extends Vehicule {\n        Moto(String marque) {\n            super(marque);\n        }\n\n        @Override\n        double vitesseMax() {\n            // TODO: retournez 200.0\n            return 0;\n        }\n    }\n\n    public static void main(String[] args) {\n        Vehicule[] vehicules = {\n            new VoitureElectrique("Tesla", 500),\n            new Moto("Yamaha")\n        };\n\n        for (Vehicule v : vehicules) {\n            v.afficher();\n            if (v instanceof Rechargeable) {\n                Rechargeable r = (Rechargeable) v;\n                System.out.println("  Autonomie : " + r.autonomie() + " km");\n            }\n        }\n    }\n}',
    E'public class Main {\n\n    abstract static class Vehicule {\n        String marque;\n\n        Vehicule(String marque) {\n            this.marque = marque;\n        }\n\n        abstract double vitesseMax();\n\n        void afficher() {\n            System.out.println(marque + " - vitesse max : " + vitesseMax() + " km/h");\n        }\n    }\n\n    interface Rechargeable {\n        int autonomie();\n    }\n\n    static class VoitureElectrique extends Vehicule implements Rechargeable {\n        int autonomieKm;\n\n        VoitureElectrique(String marque, int autonomieKm) {\n            super(marque);\n            this.autonomieKm = autonomieKm;\n        }\n\n        @Override\n        double vitesseMax() {\n            return 150.0;\n        }\n\n        @Override\n        public int autonomie() {\n            return autonomieKm;\n        }\n    }\n\n    static class Moto extends Vehicule {\n        Moto(String marque) {\n            super(marque);\n        }\n\n        @Override\n        double vitesseMax() {\n            return 200.0;\n        }\n    }\n\n    public static void main(String[] args) {\n        Vehicule[] vehicules = {\n            new VoitureElectrique("Tesla", 500),\n            new Moto("Yamaha")\n        };\n\n        for (Vehicule v : vehicules) {\n            v.afficher();\n            if (v instanceof Rechargeable) {\n                Rechargeable r = (Rechargeable) v;\n                System.out.println("  Autonomie : " + r.autonomie() + " km");\n            }\n        }\n    }\n}',
    'output.contains("Tesla") && output.contains("150.0") && output.contains("500") && output.contains("Yamaha") && output.contains("200.0")',
    E'VoitureElectrique constructeur : la PREMIERE instruction doit etre super(marque) avant this.autonomieKm = autonomieKm. vitesseMax() pour VoitureElectrique : retournez 150.0. vitesseMax() pour Moto : retournez 200.0. autonomie() : retournez autonomieKm. instanceof Rechargeable permet de verifier si un Vehicule est aussi rechargeable avant de caster et d appeler autonomie(). VoitureElectrique implements les deux contrats : la classe abstraite Vehicule (via extends) et l interface Rechargeable (via implements).',
    'HARD', 100, 3
FROM lessons l WHERE l.slug = 'classes-abstraites-interfaces';
