-- V25: Exercices Encapsulation Avancee (lecon 4 POO)

-- =============================================
-- EXERCICE 1 : Compte Bancaire (EASY)
-- =============================================

INSERT INTO exercises (lesson_id, title, description, starter_code, solution_code, test_code, hints, difficulty, xp_reward, order_index)
SELECT l.id,
    'Compte Bancaire',
    'Implementez getSolde() qui retourne le champ prive solde, et deposer(double montant) qui ajoute montant a solde si montant > 0 et affiche "Depot de X euros.", sinon affiche "Montant invalide.". La classe CompteBancaire encapsule son solde pour empecher toute modification directe depuis l exterieur.',
    E'public class Main {\n\n    static class CompteBancaire {\n        private String titulaire;\n        private double solde;\n\n        CompteBancaire(String titulaire, double soldeInitial) {\n            this.titulaire = titulaire;\n            this.solde = soldeInitial;\n        }\n\n        public double getSolde() {\n            // TODO: retournez solde\n            return 0;\n        }\n\n        public void deposer(double montant) {\n            // TODO: si montant > 0, ajoutez montant a solde\n            // et affichez "Depot de " + montant + " euros."\n            // sinon affichez "Montant invalide."\n        }\n    }\n\n    public static void main(String[] args) {\n        CompteBancaire c = new CompteBancaire("Alice", 500);\n        c.deposer(200);\n        c.deposer(-50);\n        System.out.println("Solde : " + c.getSolde());\n    }\n}',
    E'public class Main {\n\n    static class CompteBancaire {\n        private String titulaire;\n        private double solde;\n\n        CompteBancaire(String titulaire, double soldeInitial) {\n            this.titulaire = titulaire;\n            this.solde = soldeInitial;\n        }\n\n        public double getSolde() {\n            return solde;\n        }\n\n        public void deposer(double montant) {\n            if (montant > 0) {\n                solde = solde + montant;\n                System.out.println("Depot de " + montant + " euros.");\n            } else {\n                System.out.println("Montant invalide.");\n            }\n        }\n    }\n\n    public static void main(String[] args) {\n        CompteBancaire c = new CompteBancaire("Alice", 500);\n        c.deposer(200);\n        c.deposer(-50);\n        System.out.println("Solde : " + c.getSolde());\n    }\n}',
    'output.contains("Depot de 200.0 euros.") && output.contains("Montant invalide.") && output.contains("700.0")',
    E'getSolde() : retournez simplement le champ solde avec return solde;. deposer() : utilisez un if pour verifier si montant > 0. Si oui, faites solde = solde + montant; puis affichez le message avec System.out.println("Depot de " + montant + " euros.");. Si non, affichez "Montant invalide.". Le solde initial est 500, apres depot de 200 il vaut 700. La tentative avec -50 est invalide et n affecte pas le solde.',
    'EASY', 50, 1
FROM lessons l WHERE l.slug = 'encapsulation-avancee';

-- =============================================
-- EXERCICE 2 : Produit avec Validation (MEDIUM)
-- =============================================

INSERT INTO exercises (lesson_id, title, description, starter_code, solution_code, test_code, hints, difficulty, xp_reward, order_index)
SELECT l.id,
    'Produit avec Validation',
    'Implementez getNom() qui retourne nom, getPrix() qui retourne prix, et setPrix(double prix) qui met a jour this.prix uniquement si prix > 0, sinon affiche "Prix invalide.". Cette validation empeche de stocker un prix negatif ou nul. Testez avec un prix valide puis un prix invalide pour verifier que la valeur est conservee.',
    E'public class Main {\n\n    static class Produit {\n        private String nom;\n        private double prix;\n\n        Produit(String nom, double prixInitial) {\n            this.nom = nom;\n            this.prix = prixInitial;\n        }\n\n        public String getNom() {\n            // TODO: retournez nom\n            return "";\n        }\n\n        public double getPrix() {\n            // TODO: retournez prix\n            return 0;\n        }\n\n        public void setPrix(double prix) {\n            // TODO: si prix > 0, mettez a jour this.prix\n            // sinon affichez "Prix invalide."\n        }\n    }\n\n    public static void main(String[] args) {\n        Produit p = new Produit("Livre", 12.5);\n        System.out.println(p.getNom() + " : " + p.getPrix() + " euros");\n        p.setPrix(15.0);\n        System.out.println("Nouveau prix : " + p.getPrix() + " euros");\n        p.setPrix(-3.0);\n        System.out.println("Prix final : " + p.getPrix() + " euros");\n    }\n}',
    E'public class Main {\n\n    static class Produit {\n        private String nom;\n        private double prix;\n\n        Produit(String nom, double prixInitial) {\n            this.nom = nom;\n            this.prix = prixInitial;\n        }\n\n        public String getNom() {\n            return nom;\n        }\n\n        public double getPrix() {\n            return prix;\n        }\n\n        public void setPrix(double prix) {\n            if (prix > 0) {\n                this.prix = prix;\n            } else {\n                System.out.println("Prix invalide.");\n            }\n        }\n    }\n\n    public static void main(String[] args) {\n        Produit p = new Produit("Livre", 12.5);\n        System.out.println(p.getNom() + " : " + p.getPrix() + " euros");\n        p.setPrix(15.0);\n        System.out.println("Nouveau prix : " + p.getPrix() + " euros");\n        p.setPrix(-3.0);\n        System.out.println("Prix final : " + p.getPrix() + " euros");\n    }\n}',
    'output.contains("Livre") && output.contains("12.5") && output.contains("15.0") && output.contains("Prix invalide.")',
    E'getNom() : return nom; et getPrix() : return prix; sont simples. Pour setPrix() : if (prix > 0) { this.prix = prix; } else { System.out.println("Prix invalide."); }. Attention a la difference entre le parametre prix et le champ this.prix : sans this, Java ne saurait pas lequel modifier. Apres setPrix(15.0) le prix passe a 15.0. Apres setPrix(-3.0) le prix reste a 15.0 car la condition prix > 0 est fausse.',
    'MEDIUM', 75, 2
FROM lessons l WHERE l.slug = 'encapsulation-avancee';

-- =============================================
-- EXERCICE 3 : Etudiant avec Notes (HARD)
-- =============================================

INSERT INTO exercises (lesson_id, title, description, starter_code, solution_code, test_code, hints, difficulty, xp_reward, order_index)
SELECT l.id,
    'Etudiant avec Notes',
    'Completez addNote() qui ajoute une note dans le tableau si nbNotes < 5, calculerMoyenne() qui calcule la moyenne des nbNotes notes enregistrees (retournez 0 si nbNotes == 0), et getMention() qui retourne "Tres Bien" si moyenne >= 16, "Bien" si >= 14, "Assez Bien" si >= 12, "Passable" sinon. Les champs sont prives pour garantir la coherence des donnees.',
    E'public class Main {\n\n    static class Etudiant {\n        private String nom;\n        private double[] notes;\n        private int nbNotes;\n\n        Etudiant(String nom) {\n            this.nom = nom;\n            this.notes = new double[5];\n            this.nbNotes = 0;\n        }\n\n        public String getNom() { return nom; }\n\n        public void addNote(double note) {\n            // TODO: si nbNotes < 5, stockez note dans notes[nbNotes]\n            // et incrementez nbNotes\n        }\n\n        public double calculerMoyenne() {\n            // TODO: si nbNotes == 0 retournez 0\n            // sinon calculez et retournez la moyenne des nbNotes notes\n            return 0;\n        }\n\n        public String getMention() {\n            // TODO: retournez "Tres Bien" si moyenne >= 16\n            // "Bien" si >= 14, "Assez Bien" si >= 12, "Passable" sinon\n            return "";\n        }\n    }\n\n    public static void main(String[] args) {\n        Etudiant e = new Etudiant("Marie");\n        e.addNote(15);\n        e.addNote(17);\n        e.addNote(14);\n        double moyenne = e.calculerMoyenne();\n        System.out.println(e.getNom() + " - Moyenne : " + moyenne);\n        System.out.println("Mention : " + e.getMention());\n    }\n}',
    E'public class Main {\n\n    static class Etudiant {\n        private String nom;\n        private double[] notes;\n        private int nbNotes;\n\n        Etudiant(String nom) {\n            this.nom = nom;\n            this.notes = new double[5];\n            this.nbNotes = 0;\n        }\n\n        public String getNom() { return nom; }\n\n        public void addNote(double note) {\n            if (nbNotes < 5) {\n                notes[nbNotes] = note;\n                nbNotes++;\n            }\n        }\n\n        public double calculerMoyenne() {\n            if (nbNotes == 0) return 0;\n            double somme = 0;\n            for (int i = 0; i < nbNotes; i++) {\n                somme = somme + notes[i];\n            }\n            return somme / nbNotes;\n        }\n\n        public String getMention() {\n            double moyenne = calculerMoyenne();\n            if (moyenne >= 16) return "Tres Bien";\n            if (moyenne >= 14) return "Bien";\n            if (moyenne >= 12) return "Assez Bien";\n            return "Passable";\n        }\n    }\n\n    public static void main(String[] args) {\n        Etudiant e = new Etudiant("Marie");\n        e.addNote(15);\n        e.addNote(17);\n        e.addNote(14);\n        double moyenne = e.calculerMoyenne();\n        System.out.println(e.getNom() + " - Moyenne : " + moyenne);\n        System.out.println("Mention : " + e.getMention());\n    }\n}',
    'output.contains("Marie") && output.contains("15.3") && output.contains("Bien")',
    E'addNote() : if (nbNotes < 5) { notes[nbNotes] = note; nbNotes++; }. calculerMoyenne() : parcourez le tableau jusqu a nbNotes avec une boucle for, cumulez la somme, puis retournez somme / nbNotes. getMention() : appelez calculerMoyenne() puis utilisez des if/else. 15+17+14 = 46, divise par 3 = 15.33. La moyenne 15.33 est >= 14 mais < 16, donc la mention est "Bien". Utilisez nbNotes et non notes.length pour ne compter que les notes effectivement ajoutees.',
    'HARD', 100, 3
FROM lessons l WHERE l.slug = 'encapsulation-avancee';
