-- V44: Exercices Exceptions personnalisees (EASY / MEDIUM / HARD)

-- =============================================
-- EXERCICE 1 : NoteInvalideException (EASY)
-- =============================================

INSERT INTO exercises (lesson_id, title, difficulty, description, starter_code, solution_code, test_code, hints, xp_reward, order_index)
SELECT l.id,
    'NoteInvalideException',
    'EASY',
    'Creez une exception personnalisee NoteInvalideException pour signaler qu une note est hors de la plage 0-20. Utilisez-la dans une methode validerNote() et testez les cas valides et invalides.',
    E'public class Main {\n\n    // Creez ici la classe NoteInvalideException\n    // Elle etend Exception\n    // Elle prend un int note en parametre\n    // Message : "Note invalide : X. La note doit etre entre 0 et 20."\n\n    public static void validerNote(int note) throws NoteInvalideException {\n        // Si note < 0 ou note > 20, lancez une NoteInvalideException\n        // Sinon affichez : "Note valide : X/20"\n    }\n\n    public static void main(String[] args) {\n        try {\n            validerNote(15);\n            validerNote(25);\n        } catch (NoteInvalideException e) {\n            System.out.println("Erreur : " + e.getMessage());\n        }\n\n        try {\n            validerNote(-3);\n        } catch (NoteInvalideException e) {\n            System.out.println("Erreur : " + e.getMessage());\n        }\n    }\n}',
    E'public class Main {\n\n    static class NoteInvalideException extends Exception {\n        public NoteInvalideException(int note) {\n            super("Note invalide : " + note + ". La note doit etre entre 0 et 20.");\n        }\n    }\n\n    public static void validerNote(int note) throws NoteInvalideException {\n        if (note < 0 || note > 20) {\n            throw new NoteInvalideException(note);\n        }\n        System.out.println("Note valide : " + note + "/20");\n    }\n\n    public static void main(String[] args) {\n        try {\n            validerNote(15);\n            validerNote(25);\n        } catch (NoteInvalideException e) {\n            System.out.println("Erreur : " + e.getMessage());\n        }\n\n        try {\n            validerNote(-3);\n        } catch (NoteInvalideException e) {\n            System.out.println("Erreur : " + e.getMessage());\n        }\n    }\n}',
    'output.contains("Note valide : 15/20") && output.contains("Note invalide : 25") && output.contains("Note invalide : -3")',
    '["Declarez NoteInvalideException comme static class dans Main, elle etend Exception", "Le constructeur prend un int et appelle super() avec un message incluant la valeur invalide", "Dans validerNote(), utilisez throw new NoteInvalideException(note) si la note est hors plage"]',
    30,
    1
FROM lessons l WHERE l.slug = 'exceptions-personnalisees';

-- =============================================
-- EXERCICE 2 : SoldeInsuffisantException (MEDIUM)
-- =============================================

INSERT INTO exercises (lesson_id, title, difficulty, description, starter_code, solution_code, test_code, hints, xp_reward, order_index)
SELECT l.id,
    'SoldeInsuffisantException',
    'MEDIUM',
    'Simulez un compte bancaire avec une exception metier SoldeInsuffisantException qui stocke le solde actuel et le montant demande. Implementez les methodes deposer() et retirer() avec la gestion d erreur appropriee.',
    E'public class Main {\n\n    // Creez SoldeInsuffisantException extends Exception\n    // Avec deux champs : double solde et double montant\n    // Message : "Solde insuffisant : X EUR disponibles, Y EUR demandes"\n    // Ajoutez getters getSolde() et getMontant()\n\n    static double compte = 200.0;\n\n    public static void deposer(double montant) {\n        compte += montant;\n        System.out.println("Depot de " + montant + " EUR. Nouveau solde : " + compte + " EUR");\n    }\n\n    public static void retirer(double montant) throws SoldeInsuffisantException {\n        // Si montant > compte, lancez SoldeInsuffisantException(compte, montant)\n        // Sinon : compte -= montant et affichez\n        // "Retrait de X EUR. Nouveau solde : Y EUR"\n    }\n\n    public static void main(String[] args) {\n        deposer(50.0);\n        try {\n            retirer(100.0);\n            retirer(300.0);\n        } catch (SoldeInsuffisantException e) {\n            System.out.println("Refus : " + e.getMessage());\n            System.out.println("Vous avez " + e.getSolde() + " EUR");\n        }\n    }\n}',
    E'public class Main {\n\n    static class SoldeInsuffisantException extends Exception {\n        private double solde;\n        private double montant;\n\n        public SoldeInsuffisantException(double solde, double montant) {\n            super("Solde insuffisant : " + solde + " EUR disponibles, " + montant + " EUR demandes");\n            this.solde = solde;\n            this.montant = montant;\n        }\n\n        public double getSolde() { return solde; }\n        public double getMontant() { return montant; }\n    }\n\n    static double compte = 200.0;\n\n    public static void deposer(double montant) {\n        compte += montant;\n        System.out.println("Depot de " + montant + " EUR. Nouveau solde : " + compte + " EUR");\n    }\n\n    public static void retirer(double montant) throws SoldeInsuffisantException {\n        if (montant > compte) {\n            throw new SoldeInsuffisantException(compte, montant);\n        }\n        compte -= montant;\n        System.out.println("Retrait de " + montant + " EUR. Nouveau solde : " + compte + " EUR");\n    }\n\n    public static void main(String[] args) {\n        deposer(50.0);\n        try {\n            retirer(100.0);\n            retirer(300.0);\n        } catch (SoldeInsuffisantException e) {\n            System.out.println("Refus : " + e.getMessage());\n            System.out.println("Vous avez " + e.getSolde() + " EUR");\n        }\n    }\n}',
    'output.contains("Depot de 50.0 EUR") && output.contains("Retrait de 100.0 EUR") && output.contains("Solde insuffisant") && output.contains("300.0 EUR demandes") && output.contains("Vous avez")',
    '["SoldeInsuffisantException stocke deux champs double avec des getters", "Le constructeur appelle super() avec un message qui inclut les deux valeurs", "Dans retirer(), comparez montant > compte avant de soustraire"]',
    50,
    2
FROM lessons l WHERE l.slug = 'exceptions-personnalisees';

-- =============================================
-- EXERCICE 3 : Systeme de Validation (HARD)
-- =============================================

INSERT INTO exercises (lesson_id, title, difficulty, description, starter_code, solution_code, test_code, hints, xp_reward, order_index)
SELECT l.id,
    'Systeme de Validation',
    'HARD',
    'Creez un systeme de validation complet pour un formulaire d inscription. Implementez trois exceptions personnalisees (PseudoInvalideException, MotDePasseInvalideException, EmailInvalideException) et une methode validerInscription() qui les utilise.',
    E'public class Main {\n\n    // Creez 3 exceptions etendant Exception :\n    // PseudoInvalideException(String pseudo) :\n    //   message : "Pseudo invalide : [pseudo]. Minimum 3 caracteres."\n    // MotDePasseInvalideException() :\n    //   message : "Mot de passe invalide. Minimum 8 caracteres."\n    // EmailInvalideException(String email) :\n    //   message : "Email invalide : [email]. Doit contenir @."\n\n    public static void validerInscription(String pseudo, String motDePasse, String email)\n            throws PseudoInvalideException, MotDePasseInvalideException, EmailInvalideException {\n        // Validez dans cet ordre :\n        // 1. pseudo.length() < 3 -> PseudoInvalideException\n        // 2. motDePasse.length() < 8 -> MotDePasseInvalideException\n        // 3. !email.contains("@") -> EmailInvalideException\n        // Si tout est valide : affichez "Inscription reussie pour : [pseudo]"\n    }\n\n    public static void main(String[] args) {\n        String[][] cas = {\n            {"Al", "motdepasse123", "alice@mail.com"},\n            {"Alice", "mdp", "alice@mail.com"},\n            {"Alice", "motdepasse123", "alicesansarobase"},\n            {"Alice", "motdepasse123", "alice@mail.com"}\n        };\n\n        for (String[] c : cas) {\n            try {\n                validerInscription(c[0], c[1], c[2]);\n            } catch (PseudoInvalideException | MotDePasseInvalideException | EmailInvalideException e) {\n                System.out.println("Erreur : " + e.getMessage());\n            }\n        }\n    }\n}',
    E'public class Main {\n\n    static class PseudoInvalideException extends Exception {\n        public PseudoInvalideException(String pseudo) {\n            super("Pseudo invalide : " + pseudo + ". Minimum 3 caracteres.");\n        }\n    }\n\n    static class MotDePasseInvalideException extends Exception {\n        public MotDePasseInvalideException() {\n            super("Mot de passe invalide. Minimum 8 caracteres.");\n        }\n    }\n\n    static class EmailInvalideException extends Exception {\n        public EmailInvalideException(String email) {\n            super("Email invalide : " + email + ". Doit contenir @.");\n        }\n    }\n\n    public static void validerInscription(String pseudo, String motDePasse, String email)\n            throws PseudoInvalideException, MotDePasseInvalideException, EmailInvalideException {\n        if (pseudo.length() < 3) {\n            throw new PseudoInvalideException(pseudo);\n        }\n        if (motDePasse.length() < 8) {\n            throw new MotDePasseInvalideException();\n        }\n        if (!email.contains("@")) {\n            throw new EmailInvalideException(email);\n        }\n        System.out.println("Inscription reussie pour : " + pseudo);\n    }\n\n    public static void main(String[] args) {\n        String[][] cas = {\n            {"Al", "motdepasse123", "alice@mail.com"},\n            {"Alice", "mdp", "alice@mail.com"},\n            {"Alice", "motdepasse123", "alicesansarobase"},\n            {"Alice", "motdepasse123", "alice@mail.com"}\n        };\n\n        for (String[] c : cas) {\n            try {\n                validerInscription(c[0], c[1], c[2]);\n            } catch (PseudoInvalideException | MotDePasseInvalideException | EmailInvalideException e) {\n                System.out.println("Erreur : " + e.getMessage());\n            }\n        }\n    }\n}',
    'output.contains("Pseudo invalide : Al") && output.contains("Mot de passe invalide") && output.contains("Email invalide : alicesansarobase") && output.contains("Inscription reussie pour : Alice")',
    '["Creez chaque exception comme static class dans Main avec extends Exception", "Pour le multi-catch, utilisez la syntaxe : catch (TypeA | TypeB | TypeC e)", "Lancez les exceptions dans l ordre : pseudo, mot de passe, email (la premiere erreur trouvee arrete la validation)"]',
    80,
    3
FROM lessons l WHERE l.slug = 'exceptions-personnalisees';
