-- V7: Exercice - Calculateur d age en jours

-- =============================================
-- EXERCICE : Calculateur d age en jours
-- =============================================

INSERT INTO exercises (lesson_id, title, description, starter_code, solution_code, test_code, hints, difficulty, xp_reward, order_index)
SELECT l.id,
    'Calculateur d age en jours',
    E'CONTEXTE\n\nVous developpez une fonctionnalite pour une application de sante qui affiche l age d un utilisateur de differentes facons pour le rendre plus parlant.\n\nOBJECTIFS D APPRENTISSAGE\n- Utiliser les types primitifs int et double\n- Effectuer des calculs arithmetiques enchaines\n- Convertir entre differents types numeriques\n- Eviter le piege de la division entiere\n\nSPECIFICATIONS\n\nA partir d un age en annees (type int), calculez et affichez :\n1. L age en jours (approximation : 1 annee = 365 jours)\n2. L age en heures (1 jour = 24 heures)\n3. L age en minutes (1 heure = 60 minutes)\n4. L age moyen en mois (avec decimales, 1 annee = 12 mois)\n\nEXEMPLE DE SORTIE ATTENDUE pour age = 20 :\n  Age en jours : 7300\n  Age en heures : 175200\n  Age en minutes : 10512000\n  Age en mois : 240.0\n\nQUESTIONS DE REFLEXION\n- Quel type utiliser pour les heures et minutes ? Pourquoi pas int ?\n- Que se passe-t-il si vous calculez les mois avec deux int sans cast ?\n- Comment afficher 240.0 plutot que 240 pour les mois ?',
    E'public class Main {\n    public static void main(String[] args) {\n        int ageAnnees = 20;\n\n        // 1. Calculez l age en jours (365 jours par an)\n        int ageJours = 0; // a completer\n\n        // 2. Calculez l age en heures (24 heures par jour)\n        long ageHeures = 0; // a completer\n\n        // 3. Calculez l age en minutes (60 minutes par heure)\n        long ageMinutes = 0; // a completer\n\n        // 4. Calculez l age en mois avec decimales (12 mois par an)\n        double ageMois = 0; // a completer\n\n        System.out.println("Age en jours : " + ageJours);\n        System.out.println("Age en heures : " + ageHeures);\n        System.out.println("Age en minutes : " + ageMinutes);\n        System.out.println("Age en mois : " + ageMois);\n    }\n}',
    E'public class Main {\n    public static void main(String[] args) {\n        int ageAnnees = 20;\n\n        // 1. Age en jours\n        int ageJours = ageAnnees * 365;\n\n        // 2. Age en heures (utiliser long car la valeur depasse Integer.MAX_VALUE pour les grands ages)\n        long ageHeures = (long) ageJours * 24;\n\n        // 3. Age en minutes\n        long ageMinutes = ageHeures * 60;\n\n        // 4. Age en mois avec decimales (cast necessaire pour eviter la division entiere)\n        double ageMois = (double) ageAnnees * 12;\n\n        System.out.println("Age en jours : " + ageJours);\n        System.out.println("Age en heures : " + ageHeures);\n        System.out.println("Age en minutes : " + ageMinutes);\n        System.out.println("Age en mois : " + ageMois);\n    }\n}',
    'output.contains("7300") && output.contains("175200") && output.contains("10512000") && output.contains("240.0")',
    E'Indice 1 : Pour les jours, multipliez simplement ageAnnees par 365 avec des int.\nIndice 2 : Pour les heures, utilisez long et forcez la conversion avec (long) ageJours * 24 pour eviter un depassement avec des ages eleves.\nIndice 3 : Pour les minutes, long ageMinutes = ageHeures * 60 fonctionne car ageHeures est deja un long.\nIndice 4 : Pour les mois avec decimales, ecrivez (double) ageAnnees * 12. Sans le cast, la multiplication de deux int donne un int, puis la conversion en double n ajoute pas de decimales.',
    'MEDIUM', 150, 3
FROM lessons l WHERE l.slug = 'variables';
