-- V87: Exercices Lecon 1 - Modelisation Meal et Customer

-- =============================================
-- EXERCICE 1 : La Classe Meal (EASY)
-- =============================================

INSERT INTO exercises (lesson_id, title, difficulty, description, starter_code, solution_code, test_code, hints, xp_reward, order_index)
SELECT l.id,
    'La Classe Meal',
    'EASY',
    'Definissez la classe Meal avec trois champs prives : id (int), name (String) et price (double). Ajoutez un constructeur, des getters getId(), getName(), getPrice(), et une methode toString() qui retourne "#id - name : price EUR". Instanciez 3 repas et affichez-les.',
    E'// TODO: Definissez la classe Meal avant la classe Main\n// Champs prives : id (int), name (String), price (double)\n// Constructeur : Meal(int id, String name, double price)\n// Getters : getId(), getName(), getPrice()\n// toString() retourne : "#id - name : price EUR"\n// Exemple : "#1 - Pizza Margherita : 12.5 EUR"\n\npublic class Main {\n    public static void main(String[] args) {\n        Meal m1 = new Meal(1, "Pizza Margherita", 12.5);\n        Meal m2 = new Meal(2, "Burger Classic", 9.9);\n        Meal m3 = new Meal(3, "Salade Caesar", 8.5);\n\n        System.out.println("--- Liste des repas ---");\n        System.out.println(m1);\n        System.out.println(m2);\n        System.out.println(m3);\n    }\n}',
    E'class Meal {\n    private int id;\n    private String name;\n    private double price;\n\n    public Meal(int id, String name, double price) {\n        this.id = id;\n        this.name = name;\n        this.price = price;\n    }\n\n    public int getId() { return id; }\n    public String getName() { return name; }\n    public double getPrice() { return price; }\n\n    @Override\n    public String toString() {\n        return "#" + id + " - " + name + " : " + price + " EUR";\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Meal m1 = new Meal(1, "Pizza Margherita", 12.5);\n        Meal m2 = new Meal(2, "Burger Classic", 9.9);\n        Meal m3 = new Meal(3, "Salade Caesar", 8.5);\n\n        System.out.println("--- Liste des repas ---");\n        System.out.println(m1);\n        System.out.println(m2);\n        System.out.println(m3);\n    }\n}',
    'output.contains("--- Liste des repas ---") && output.contains("#1 - Pizza Margherita : 12.5 EUR") && output.contains("#2 - Burger Classic : 9.9 EUR") && output.contains("#3 - Salade Caesar : 8.5 EUR")',
    '["Definissez la classe Meal AVANT la classe Main dans le meme fichier", "Les champs doivent etre private : private int id; private String name; private double price;", "toString() est appelee automatiquement par System.out.println() : retournez la chaine formatee avec # + id + \" - \" + name + \" : \" + price + \" EUR\""]',
    30,
    1
FROM lessons l WHERE l.slug = 'mvc-modeles';

-- =============================================
-- EXERCICE 2 : La Classe Customer (MEDIUM)
-- =============================================

INSERT INTO exercises (lesson_id, title, difficulty, description, starter_code, solution_code, test_code, hints, xp_reward, order_index)
SELECT l.id,
    'La Classe Customer',
    'MEDIUM',
    'Definissez la classe Customer avec trois champs prives : id (int), name (String) et address (String). Ajoutez un constructeur, des getters getId(), getName(), getAddress(), et une methode toString() qui retourne "#id - name | address". Instanciez 3 clients et affichez-les.',
    E'// TODO: Definissez la classe Customer avant la classe Main\n// Champs prives : id (int), name (String), address (String)\n// Constructeur : Customer(int id, String name, String address)\n// Getters : getId(), getName(), getAddress()\n// toString() retourne : "#id - name | address"\n// Exemple : "#1 - Jean Dupont | 12 rue de la Paix, Paris"\n\npublic class Main {\n    public static void main(String[] args) {\n        Customer c1 = new Customer(1, "Jean Dupont", "12 rue de la Paix, Paris");\n        Customer c2 = new Customer(2, "Marie Martin", "5 avenue Victor Hugo, Lyon");\n        Customer c3 = new Customer(3, "Paul Bernard", "8 boulevard Gambetta, Marseille");\n\n        System.out.println("--- Liste des clients ---");\n        System.out.println(c1);\n        System.out.println(c2);\n        System.out.println(c3);\n    }\n}',
    E'class Customer {\n    private int id;\n    private String name;\n    private String address;\n\n    public Customer(int id, String name, String address) {\n        this.id = id;\n        this.name = name;\n        this.address = address;\n    }\n\n    public int getId() { return id; }\n    public String getName() { return name; }\n    public String getAddress() { return address; }\n\n    @Override\n    public String toString() {\n        return "#" + id + " - " + name + " | " + address;\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Customer c1 = new Customer(1, "Jean Dupont", "12 rue de la Paix, Paris");\n        Customer c2 = new Customer(2, "Marie Martin", "5 avenue Victor Hugo, Lyon");\n        Customer c3 = new Customer(3, "Paul Bernard", "8 boulevard Gambetta, Marseille");\n\n        System.out.println("--- Liste des clients ---");\n        System.out.println(c1);\n        System.out.println(c2);\n        System.out.println(c3);\n    }\n}',
    'output.contains("--- Liste des clients ---") && output.contains("#1 - Jean Dupont | 12 rue de la Paix, Paris") && output.contains("#2 - Marie Martin | 5 avenue Victor Hugo, Lyon") && output.contains("#3 - Paul Bernard")',
    '["La structure est identique a Meal : private fields, constructeur, getters, toString()", "Le separateur dans toString() est \" | \" (avec espaces autour de la barre verticale)", "Pensez a inclure l adresse complete dans toString() : return \"#\" + id + \" - \" + name + \" | \" + address;"]',
    40,
    2
FROM lessons l WHERE l.slug = 'mvc-modeles';

-- =============================================
-- EXERCICE 3 : Commande - Lier Meal et Customer (HARD)
-- =============================================

INSERT INTO exercises (lesson_id, title, difficulty, description, starter_code, solution_code, test_code, hints, xp_reward, order_index)
SELECT l.id,
    'Commande - Lier Meal et Customer',
    'HARD',
    'Les classes Meal et Customer sont deja fournies. Implementez la classe Order qui relie un client a un repas. Order a trois champs : id (int), customer (Customer), meal (Meal). Son toString() retourne "Commande #id : customerName -> mealName (price EUR)". Creez 2 commandes, affichez-les et calculez le total.',
    E'class Meal {\n    private int id;\n    private String name;\n    private double price;\n    public Meal(int id, String name, double price) { this.id=id; this.name=name; this.price=price; }\n    public int getId() { return id; }\n    public String getName() { return name; }\n    public double getPrice() { return price; }\n    public String toString() { return "#"+id+" - "+name+" : "+price+" EUR"; }\n}\n\nclass Customer {\n    private int id;\n    private String name;\n    private String address;\n    public Customer(int id, String name, String address) { this.id=id; this.name=name; this.address=address; }\n    public int getId() { return id; }\n    public String getName() { return name; }\n    public String getAddress() { return address; }\n    public String toString() { return "#"+id+" - "+name+" | "+address; }\n}\n\n// TODO: Definissez la classe Order ici\n// Champs : id (int), customer (Customer), meal (Meal)\n// Constructeur : Order(int id, Customer customer, Meal meal)\n// Getters : getId(), getCustomer(), getMeal()\n// toString() : "Commande #id : customerName -> mealName (price EUR)"\n\npublic class Main {\n    public static void main(String[] args) {\n        Meal pizza = new Meal(1, "Pizza Margherita", 12.5);\n        Meal burger = new Meal(2, "Burger Classic", 9.9);\n        Customer jean = new Customer(1, "Jean Dupont", "12 rue de la Paix, Paris");\n        Customer marie = new Customer(2, "Marie Martin", "5 avenue Victor Hugo, Lyon");\n\n        Order o1 = new Order(1, jean, pizza);\n        Order o2 = new Order(2, marie, burger);\n\n        System.out.println("--- Commandes ---");\n        System.out.println(o1);\n        System.out.println(o2);\n        double total = pizza.getPrice() + burger.getPrice();\n        System.out.println("Total : " + total + " EUR");\n    }\n}',
    E'class Meal {\n    private int id;\n    private String name;\n    private double price;\n    public Meal(int id, String name, double price) { this.id=id; this.name=name; this.price=price; }\n    public int getId() { return id; }\n    public String getName() { return name; }\n    public double getPrice() { return price; }\n    public String toString() { return "#"+id+" - "+name+" : "+price+" EUR"; }\n}\n\nclass Customer {\n    private int id;\n    private String name;\n    private String address;\n    public Customer(int id, String name, String address) { this.id=id; this.name=name; this.address=address; }\n    public int getId() { return id; }\n    public String getName() { return name; }\n    public String getAddress() { return address; }\n    public String toString() { return "#"+id+" - "+name+" | "+address; }\n}\n\nclass Order {\n    private int id;\n    private Customer customer;\n    private Meal meal;\n\n    public Order(int id, Customer customer, Meal meal) {\n        this.id = id;\n        this.customer = customer;\n        this.meal = meal;\n    }\n\n    public int getId() { return id; }\n    public Customer getCustomer() { return customer; }\n    public Meal getMeal() { return meal; }\n\n    @Override\n    public String toString() {\n        return "Commande #" + id + " : " + customer.getName()\n            + " -> " + meal.getName()\n            + " (" + meal.getPrice() + " EUR)";\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Meal pizza = new Meal(1, "Pizza Margherita", 12.5);\n        Meal burger = new Meal(2, "Burger Classic", 9.9);\n        Customer jean = new Customer(1, "Jean Dupont", "12 rue de la Paix, Paris");\n        Customer marie = new Customer(2, "Marie Martin", "5 avenue Victor Hugo, Lyon");\n\n        Order o1 = new Order(1, jean, pizza);\n        Order o2 = new Order(2, marie, burger);\n\n        System.out.println("--- Commandes ---");\n        System.out.println(o1);\n        System.out.println(o2);\n        double total = pizza.getPrice() + burger.getPrice();\n        System.out.println("Total : " + total + " EUR");\n    }\n}',
    'output.contains("Commande #1 : Jean Dupont -> Pizza Margherita (12.5 EUR)") && output.contains("Commande #2 : Marie Martin -> Burger Classic (9.9 EUR)") && output.contains("Total : 22.4 EUR")',
    '["Order contient une reference vers Customer et Meal (composition) : private Customer customer; private Meal meal;", "Dans toString(), utilisez customer.getName() et meal.getName() pour recuperer les noms via les getters", "Le format exact : \"Commande #\" + id + \" : \" + customer.getName() + \" -> \" + meal.getName() + \" (\" + meal.getPrice() + \" EUR)\""]',
    50,
    3
FROM lessons l WHERE l.slug = 'mvc-modeles';
