-- V89: Exercices Lecon 2 - Le Pattern Repository

-- =============================================
-- EXERCICE 1 : MealRepository - Ajouter et Lister (EASY)
-- =============================================

INSERT INTO exercises (lesson_id, title, difficulty, description, starter_code, solution_code, test_code, hints, xp_reward, order_index)
SELECT l.id,
    'MealRepository - Ajouter et Lister',
    'EASY',
    'Implementez la classe MealRepository qui stocke des repas en memoire avec une ArrayList. Elle doit avoir un champ nextId initialise a 1, une methode add(String name, double price) qui cree un Meal avec un ID auto-incremente, et une methode all() qui retourne une copie defensive de la liste. Ajoutez 3 repas et affichez-les tous.',
    E'import java.util.ArrayList;\nimport java.util.List;\n\nclass Meal {\n    private int id;\n    private String name;\n    private double price;\n    public Meal(int id, String name, double price) { this.id=id; this.name=name; this.price=price; }\n    public int getId() { return id; }\n    public String getName() { return name; }\n    public double getPrice() { return price; }\n    public String toString() { return "#"+id+" - "+name+" : "+price+" EUR"; }\n}\n\n// TODO: Implementez la classe MealRepository\n// - private List<Meal> meals = new ArrayList<>()\n// - private int nextId = 1\n// - void add(String name, double price) -> cree un Meal avec nextId++ et l ajoute\n// - List<Meal> all() -> retourne new ArrayList<>(meals)\n\npublic class Main {\n    public static void main(String[] args) {\n        MealRepository repo = new MealRepository();\n        repo.add("Pizza Margherita", 12.5);\n        repo.add("Burger Classic", 9.9);\n        repo.add("Salade Caesar", 8.5);\n\n        System.out.println("--- Tous les repas ---");\n        for (Meal m : repo.all()) {\n            System.out.println(m);\n        }\n        System.out.println("Total : " + repo.all().size() + " repas");\n    }\n}',
    E'import java.util.ArrayList;\nimport java.util.List;\n\nclass Meal {\n    private int id;\n    private String name;\n    private double price;\n    public Meal(int id, String name, double price) { this.id=id; this.name=name; this.price=price; }\n    public int getId() { return id; }\n    public String getName() { return name; }\n    public double getPrice() { return price; }\n    public String toString() { return "#"+id+" - "+name+" : "+price+" EUR"; }\n}\n\nclass MealRepository {\n    private List<Meal> meals = new ArrayList<>();\n    private int nextId = 1;\n\n    public void add(String name, double price) {\n        meals.add(new Meal(nextId++, name, price));\n    }\n\n    public List<Meal> all() {\n        return new ArrayList<>(meals);\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        MealRepository repo = new MealRepository();\n        repo.add("Pizza Margherita", 12.5);\n        repo.add("Burger Classic", 9.9);\n        repo.add("Salade Caesar", 8.5);\n\n        System.out.println("--- Tous les repas ---");\n        for (Meal m : repo.all()) {\n            System.out.println(m);\n        }\n        System.out.println("Total : " + repo.all().size() + " repas");\n    }\n}',
    'output.contains("--- Tous les repas ---") && output.contains("#1 - Pizza Margherita : 12.5 EUR") && output.contains("#2 - Burger Classic : 9.9 EUR") && output.contains("#3 - Salade Caesar : 8.5 EUR") && output.contains("Total : 3 repas")',
    '["Declarez private List<Meal> meals = new ArrayList<>(); et private int nextId = 1; comme champs de MealRepository", "Dans add(), creez un nouveau Meal avec nextId++ : meals.add(new Meal(nextId++, name, price)); L operateur ++ postfixe utilise la valeur puis incremente", "Dans all(), retournez une copie : return new ArrayList<>(meals); pour proteger la liste interne"]',
    30,
    1
FROM lessons l WHERE l.slug = 'mvc-repository';

-- =============================================
-- EXERCICE 2 : MealRepository - Recherche et Suppression (MEDIUM)
-- =============================================

INSERT INTO exercises (lesson_id, title, difficulty, description, starter_code, solution_code, test_code, hints, xp_reward, order_index)
SELECT l.id,
    'MealRepository - Recherche et Suppression',
    'MEDIUM',
    'Completez MealRepository en ajoutant deux methodes : findById(int id) qui retourne le Meal correspondant ou null si non trouve, et delete(int id) qui supprime le repas avec cet ID en utilisant removeIf(). Testez ces deux methodes.',
    E'import java.util.ArrayList;\nimport java.util.List;\n\nclass Meal {\n    private int id;\n    private String name;\n    private double price;\n    public Meal(int id, String name, double price) { this.id=id; this.name=name; this.price=price; }\n    public int getId() { return id; }\n    public String getName() { return name; }\n    public double getPrice() { return price; }\n    public String toString() { return "#"+id+" - "+name+" : "+price+" EUR"; }\n}\n\nclass MealRepository {\n    private List<Meal> meals = new ArrayList<>();\n    private int nextId = 1;\n\n    public void add(String name, double price) {\n        meals.add(new Meal(nextId++, name, price));\n    }\n\n    public List<Meal> all() {\n        return new ArrayList<>(meals);\n    }\n\n    // TODO: implementez findById(int id)\n    // Parcourez meals avec un for-each\n    // Retournez le repas dont getId() == id\n    // Retournez null si aucun repas ne correspond\n\n    // TODO: implementez delete(int id)\n    // Utilisez meals.removeIf(meal -> meal.getId() == id)\n    // La methode retourne boolean (true si supprime, false sinon)\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        MealRepository repo = new MealRepository();\n        repo.add("Pizza Margherita", 12.5);\n        repo.add("Burger Classic", 9.9);\n        repo.add("Salade Caesar", 8.5);\n\n        Meal found = repo.findById(2);\n        System.out.println("Trouve : " + found);\n\n        repo.delete(2);\n        System.out.println("Apres suppression : " + repo.all().size() + " repas");\n\n        Meal notFound = repo.findById(2);\n        System.out.println("Introuvable : " + notFound);\n    }\n}',
    E'import java.util.ArrayList;\nimport java.util.List;\n\nclass Meal {\n    private int id;\n    private String name;\n    private double price;\n    public Meal(int id, String name, double price) { this.id=id; this.name=name; this.price=price; }\n    public int getId() { return id; }\n    public String getName() { return name; }\n    public double getPrice() { return price; }\n    public String toString() { return "#"+id+" - "+name+" : "+price+" EUR"; }\n}\n\nclass MealRepository {\n    private List<Meal> meals = new ArrayList<>();\n    private int nextId = 1;\n\n    public void add(String name, double price) {\n        meals.add(new Meal(nextId++, name, price));\n    }\n\n    public List<Meal> all() {\n        return new ArrayList<>(meals);\n    }\n\n    public Meal findById(int id) {\n        for (Meal meal : meals) {\n            if (meal.getId() == id) {\n                return meal;\n            }\n        }\n        return null;\n    }\n\n    public boolean delete(int id) {\n        return meals.removeIf(meal -> meal.getId() == id);\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        MealRepository repo = new MealRepository();\n        repo.add("Pizza Margherita", 12.5);\n        repo.add("Burger Classic", 9.9);\n        repo.add("Salade Caesar", 8.5);\n\n        Meal found = repo.findById(2);\n        System.out.println("Trouve : " + found);\n\n        repo.delete(2);\n        System.out.println("Apres suppression : " + repo.all().size() + " repas");\n\n        Meal notFound = repo.findById(2);\n        System.out.println("Introuvable : " + notFound);\n    }\n}',
    'output.contains("Trouve : #2 - Burger Classic : 9.9 EUR") && output.contains("Apres suppression : 2 repas") && output.contains("Introuvable : null")',
    '["findById : parcourez avec for (Meal meal : meals) et comparez meal.getId() == id", "Si aucun repas ne correspond, retournez null apres la boucle", "delete : utilisez meals.removeIf(meal -> meal.getId() == id) qui supprime tous les elements verifiant la condition et retourne true si au moins un element a ete supprime"]',
    40,
    2
FROM lessons l WHERE l.slug = 'mvc-repository';

-- =============================================
-- EXERCICE 3 : CustomerRepository Complet (HARD)
-- =============================================

INSERT INTO exercises (lesson_id, title, difficulty, description, starter_code, solution_code, test_code, hints, xp_reward, order_index)
SELECT l.id,
    'CustomerRepository Complet',
    'HARD',
    'Implementez la classe Customer avec des setters (setName, setAddress) en plus des getters habituels. Puis implementez CustomerRepository avec les methodes : add(String name, String address), all(), findById(int id) et update(int id, String newName, String newAddress) qui modifie le client existant via ses setters.',
    E'import java.util.ArrayList;\nimport java.util.List;\n\n// TODO: Implementez la classe Customer\n// Champs prives : id (int), name (String), address (String)\n// Constructeur : Customer(int id, String name, String address)\n// Getters : getId(), getName(), getAddress()\n// Setters : setName(String name), setAddress(String address)\n// toString() : "#id - name | address"\n\n// TODO: Implementez CustomerRepository\n// Methodes : add(String name, String address), all(), findById(int id)\n// update(int id, String newName, String newAddress)\n//   -> trouver le customer par id, puis appeler setName() et setAddress()\n\npublic class Main {\n    public static void main(String[] args) {\n        CustomerRepository repo = new CustomerRepository();\n        repo.add("Jean Dupont", "12 rue de la Paix, Paris");\n        repo.add("Marie Martin", "5 avenue Victor Hugo, Lyon");\n\n        System.out.println("--- Clients ---");\n        for (Customer c : repo.all()) {\n            System.out.println(c);\n        }\n\n        repo.update(1, "Jean Dupont", "15 rue du Commerce, Bordeaux");\n        System.out.println("Mis a jour : " + repo.findById(1));\n    }\n}',
    E'import java.util.ArrayList;\nimport java.util.List;\n\nclass Customer {\n    private int id;\n    private String name;\n    private String address;\n\n    public Customer(int id, String name, String address) {\n        this.id = id;\n        this.name = name;\n        this.address = address;\n    }\n\n    public int getId() { return id; }\n    public String getName() { return name; }\n    public String getAddress() { return address; }\n    public void setName(String name) { this.name = name; }\n    public void setAddress(String address) { this.address = address; }\n\n    @Override\n    public String toString() {\n        return "#" + id + " - " + name + " | " + address;\n    }\n}\n\nclass CustomerRepository {\n    private List<Customer> customers = new ArrayList<>();\n    private int nextId = 1;\n\n    public void add(String name, String address) {\n        customers.add(new Customer(nextId++, name, address));\n    }\n\n    public List<Customer> all() {\n        return new ArrayList<>(customers);\n    }\n\n    public Customer findById(int id) {\n        for (Customer c : customers) {\n            if (c.getId() == id) return c;\n        }\n        return null;\n    }\n\n    public void update(int id, String newName, String newAddress) {\n        Customer customer = findById(id);\n        if (customer != null) {\n            customer.setName(newName);\n            customer.setAddress(newAddress);\n        }\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        CustomerRepository repo = new CustomerRepository();\n        repo.add("Jean Dupont", "12 rue de la Paix, Paris");\n        repo.add("Marie Martin", "5 avenue Victor Hugo, Lyon");\n\n        System.out.println("--- Clients ---");\n        for (Customer c : repo.all()) {\n            System.out.println(c);\n        }\n\n        repo.update(1, "Jean Dupont", "15 rue du Commerce, Bordeaux");\n        System.out.println("Mis a jour : " + repo.findById(1));\n    }\n}',
    'output.contains("--- Clients ---") && output.contains("#1 - Jean Dupont | 12 rue de la Paix, Paris") && output.contains("#2 - Marie Martin | 5 avenue Victor Hugo, Lyon") && output.contains("Mis a jour : #1 - Jean Dupont | 15 rue du Commerce, Bordeaux")',
    '["Ajoutez des setters a Customer : public void setName(String name) { this.name = name; } et public void setAddress(String address) { this.address = address; }", "Dans update(), commencez par appeler findById(id) pour recuperer le customer, puis appelez ses setters si le resultat n est pas null", "update() modifie l objet en place dans la liste : pas besoin de supprimer et re-ajouter, les setters modifient directement l objet stocke dans customers"]',
    50,
    3
FROM lessons l WHERE l.slug = 'mvc-repository';
