-- V96: Exercices Lecon 1 - Singleton et Factory Method

-- =============================================
-- EXERCICE 1 : Logger Singleton (EASY)
-- =============================================

INSERT INTO exercises (lesson_id, title, difficulty, description, starter_code, solution_code, test_code, hints, xp_reward, order_index)
SELECT l.id,
    'Logger Singleton',
    'EASY',
    'Implementez la classe Logger avec le patron Singleton. Logger doit avoir un constructeur private, un champ static private Logger instance initialise a null, et une methode static getInstance() qui retourne l instance unique en la creant au premier appel. Ajoutez une methode log(String message) qui affiche "[LOG] " suivi du message. Verifiez que deux appels a getInstance() retournent le meme objet avec ==.',
    E'// TODO: Implementez la classe Logger avec le patron Singleton\n// - private static Logger instance = null;\n// - Constructeur private Logger() {}\n// - public static Logger getInstance() :\n//     si instance == null, cree new Logger()\n//     retourne instance\n// - public void log(String message) : affiche "[LOG] " + message\n\npublic class Main {\n    public static void main(String[] args) {\n        Logger log1 = Logger.getInstance();\n        Logger log2 = Logger.getInstance();\n\n        log1.log("Application demarree");\n        log2.log("Connexion etablie");\n        log1.log("Traitement termine");\n\n        System.out.println("Meme instance : " + (log1 == log2));\n    }\n}',
    E'class Logger {\n    private static Logger instance = null;\n\n    private Logger() {}\n\n    public static Logger getInstance() {\n        if (instance == null) {\n            instance = new Logger();\n        }\n        return instance;\n    }\n\n    public void log(String message) {\n        System.out.println("[LOG] " + message);\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Logger log1 = Logger.getInstance();\n        Logger log2 = Logger.getInstance();\n\n        log1.log("Application demarree");\n        log2.log("Connexion etablie");\n        log1.log("Traitement termine");\n\n        System.out.println("Meme instance : " + (log1 == log2));\n    }\n}',
    'output.contains("[LOG] Application demarree") && output.contains("[LOG] Connexion etablie") && output.contains("[LOG] Traitement termine") && output.contains("Meme instance : true")',
    '["Declarez private static Logger instance = null; et un constructeur private Logger() {} dans la classe", "getInstance() verifie if (instance == null) { instance = new Logger(); } puis retourne instance", "log1 == log2 sera true car les deux variables pointent vers la meme instance : getInstance() retourne toujours le meme objet"]',
    30,
    1
FROM lessons l WHERE l.slug = 'singleton-factory';

-- =============================================
-- EXERCICE 2 : ShapeFactory (MEDIUM)
-- =============================================

INSERT INTO exercises (lesson_id, title, difficulty, description, starter_code, solution_code, test_code, hints, xp_reward, order_index)
SELECT l.id,
    'ShapeFactory - Formes Geometriques',
    'MEDIUM',
    'Implementez l interface Shape avec les methodes double area() et String type(). Creez les classes Circle (constructeur avec rayon), Rectangle (largeur et hauteur) et Triangle (base et hauteur). Circle : area = Math.PI * radius * radius. Rectangle : area = width * height. Triangle : area = 0.5 * base * height. Implementez ShapeFactory.create(String type, double... params) avec "circle", "rectangle" et "triangle".',
    E'// TODO: interface Shape avec double area() et String type()\n\n// TODO: class Circle implements Shape\n// Circle(double radius)\n// area() = Math.PI * radius * radius\n// type() = "Cercle"\n\n// TODO: class Rectangle implements Shape\n// Rectangle(double width, double height)\n// area() = width * height\n// type() = "Rectangle"\n\n// TODO: class Triangle implements Shape\n// Triangle(double base, double height)\n// area() = 0.5 * base * height\n// type() = "Triangle"\n\n// TODO: class ShapeFactory\n// static Shape create(String type, double... params)\n//   "circle"    -> new Circle(params[0])\n//   "rectangle" -> new Rectangle(params[0], params[1])\n//   "triangle"  -> new Triangle(params[0], params[1])\n\npublic class Main {\n    public static void main(String[] args) {\n        Shape c = ShapeFactory.create("circle", 5.0);\n        Shape r = ShapeFactory.create("rectangle", 4.0, 6.0);\n        Shape t = ShapeFactory.create("triangle", 8.0, 3.0);\n\n        System.out.println(c.type() + " : " + Math.round(c.area()));\n        System.out.println(r.type() + " : " + r.area());\n        System.out.println(t.type() + " : " + t.area());\n    }\n}',
    E'interface Shape {\n    double area();\n    String type();\n}\n\nclass Circle implements Shape {\n    private double radius;\n    public Circle(double radius) { this.radius = radius; }\n    public double area() { return Math.PI * radius * radius; }\n    public String type() { return "Cercle"; }\n}\n\nclass Rectangle implements Shape {\n    private double width, height;\n    public Rectangle(double width, double height) { this.width = width; this.height = height; }\n    public double area() { return width * height; }\n    public String type() { return "Rectangle"; }\n}\n\nclass Triangle implements Shape {\n    private double base, height;\n    public Triangle(double base, double height) { this.base = base; this.height = height; }\n    public double area() { return 0.5 * base * height; }\n    public String type() { return "Triangle"; }\n}\n\nclass ShapeFactory {\n    public static Shape create(String type, double... params) {\n        switch (type) {\n            case "circle":    return new Circle(params[0]);\n            case "rectangle": return new Rectangle(params[0], params[1]);\n            case "triangle":  return new Triangle(params[0], params[1]);\n            default: throw new IllegalArgumentException("Type inconnu : " + type);\n        }\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Shape c = ShapeFactory.create("circle", 5.0);\n        Shape r = ShapeFactory.create("rectangle", 4.0, 6.0);\n        Shape t = ShapeFactory.create("triangle", 8.0, 3.0);\n\n        System.out.println(c.type() + " : " + Math.round(c.area()));\n        System.out.println(r.type() + " : " + r.area());\n        System.out.println(t.type() + " : " + t.area());\n    }\n}',
    'output.contains("Cercle : 79") && output.contains("Rectangle : 24.0") && output.contains("Triangle : 12.0")',
    '["L interface Shape declare double area() et String type() sans implementation", "ShapeFactory.create() prend double... params (varargs) : params[0] est le rayon pour circle, params[0] et params[1] sont largeur et hauteur pour rectangle", "Math.round(Math.PI * 25) = Math.round(78.53...) = 79 : la methode round arrondit au long le plus proche"]',
    40,
    2
FROM lessons l WHERE l.slug = 'singleton-factory';

-- =============================================
-- EXERCICE 3 : InventoryManager Singleton + ProductFactory (HARD)
-- =============================================

INSERT INTO exercises (lesson_id, title, difficulty, description, starter_code, solution_code, test_code, hints, xp_reward, order_index)
SELECT l.id,
    'InventoryManager Singleton et ProductFactory',
    'HARD',
    'Implementez l interface Product avec String name(), double price() et String info(). Creez PerishableProduct (info : "[PERISSABLE] name - price EUR (DLC: 7 jours)") et DurableProduct (info : "[DURABLE] name - price EUR (garantie: 2 ans)"). Implementez ProductFactory.create(String type, String name, double price) avec "perishable" et "durable". Implementez InventoryManager Singleton avec addProduct(Product p), listAll() et double totalPrice().',
    E'// TODO: interface Product avec String name(), double price(), String info()\n\n// TODO: class PerishableProduct implements Product\n// info() retourne "[PERISSABLE] " + name + " - " + price + " EUR (DLC: 7 jours)"\n\n// TODO: class DurableProduct implements Product\n// info() retourne "[DURABLE] " + name + " - " + price + " EUR (garantie: 2 ans)"\n\n// TODO: class ProductFactory\n// static Product create(String type, String name, double price)\n//   "perishable" -> new PerishableProduct(name, price)\n//   "durable"   -> new DurableProduct(name, price)\n\n// TODO: class InventoryManager (Singleton)\n// private static InventoryManager instance = null\n// private List<Product> products = new ArrayList<>()\n// private InventoryManager() {}\n// public static InventoryManager getInstance()\n// public void addProduct(Product p)\n// public void listAll() : affiche info() de chaque produit\n// public double totalPrice() : somme de tous les price()\n\nimport java.util.ArrayList;\nimport java.util.List;\n\npublic class Main {\n    public static void main(String[] args) {\n        InventoryManager inv1 = InventoryManager.getInstance();\n        InventoryManager inv2 = InventoryManager.getInstance();\n\n        inv1.addProduct(ProductFactory.create("durable", "Ordinateur portable", 999.99));\n        inv1.addProduct(ProductFactory.create("perishable", "Yaourt nature", 1.5));\n        inv2.addProduct(ProductFactory.create("durable", "Machine a laver", 449.0));\n\n        inv1.listAll();\n        System.out.println("Total inventaire : " + inv1.totalPrice() + " EUR");\n        System.out.println("Instance unique : " + (inv1 == inv2));\n    }\n}',
    E'import java.util.ArrayList;\nimport java.util.List;\n\ninterface Product {\n    String name();\n    double price();\n    String info();\n}\n\nclass PerishableProduct implements Product {\n    private String name;\n    private double price;\n    public PerishableProduct(String name, double price) { this.name = name; this.price = price; }\n    public String name() { return name; }\n    public double price() { return price; }\n    public String info() { return "[PERISSABLE] " + name + " - " + price + " EUR (DLC: 7 jours)"; }\n}\n\nclass DurableProduct implements Product {\n    private String name;\n    private double price;\n    public DurableProduct(String name, double price) { this.name = name; this.price = price; }\n    public String name() { return name; }\n    public double price() { return price; }\n    public String info() { return "[DURABLE] " + name + " - " + price + " EUR (garantie: 2 ans)"; }\n}\n\nclass ProductFactory {\n    public static Product create(String type, String name, double price) {\n        switch (type) {\n            case "perishable": return new PerishableProduct(name, price);\n            case "durable":    return new DurableProduct(name, price);\n            default: throw new IllegalArgumentException("Type inconnu : " + type);\n        }\n    }\n}\n\nclass InventoryManager {\n    private static InventoryManager instance = null;\n    private List<Product> products = new ArrayList<>();\n\n    private InventoryManager() {}\n\n    public static InventoryManager getInstance() {\n        if (instance == null) {\n            instance = new InventoryManager();\n        }\n        return instance;\n    }\n\n    public void addProduct(Product p) {\n        products.add(p);\n    }\n\n    public void listAll() {\n        for (Product p : products) {\n            System.out.println(p.info());\n        }\n    }\n\n    public double totalPrice() {\n        double total = 0;\n        for (Product p : products) {\n            total += p.price();\n        }\n        return total;\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        InventoryManager inv1 = InventoryManager.getInstance();\n        InventoryManager inv2 = InventoryManager.getInstance();\n\n        inv1.addProduct(ProductFactory.create("durable", "Ordinateur portable", 999.99));\n        inv1.addProduct(ProductFactory.create("perishable", "Yaourt nature", 1.5));\n        inv2.addProduct(ProductFactory.create("durable", "Machine a laver", 449.0));\n\n        inv1.listAll();\n        System.out.println("Total inventaire : " + inv1.totalPrice() + " EUR");\n        System.out.println("Instance unique : " + (inv1 == inv2));\n    }\n}',
    'output.contains("[DURABLE] Ordinateur portable - 999.99 EUR (garantie: 2 ans)") && output.contains("[PERISSABLE] Yaourt nature - 1.5 EUR (DLC: 7 jours)") && output.contains("[DURABLE] Machine a laver - 449.0 EUR (garantie: 2 ans)") && output.contains("Total inventaire : 1450.49 EUR") && output.contains("Instance unique : true")',
    '["InventoryManager Singleton : private static InventoryManager instance = null; constructeur private, getInstance() avec if (instance == null)", "ProductFactory.create() utilise un switch sur le type : \"perishable\" cree PerishableProduct, \"durable\" cree DurableProduct", "totalPrice() parcourt la liste products avec un for-each et additionne p.price() : 999.99 + 1.5 + 449.0 = 1450.49"]',
    50,
    3
FROM lessons l WHERE l.slug = 'singleton-factory';
