-- V98: Exercices Lecon 2 - Observer Pattern

-- =============================================
-- EXERCICE 1 : EventBus simple (EASY)
-- =============================================

INSERT INTO exercises (lesson_id, title, difficulty, description, starter_code, solution_code, test_code, hints, xp_reward, order_index)
SELECT l.id,
    'EventBus avec Lambdas',
    'EASY',
    'Creez l interface fonctionnelle SimpleObserver avec une seule methode void onEvent(String message). Implementez la classe EventBus avec une List<SimpleObserver> listeners, une methode subscribe(SimpleObserver o) qui ajoute a la liste, et une methode publish(String message) qui appelle onEvent() sur chaque listener. Dans le main, abonnez deux lambdas : une qui affiche "Logger: " + message et une qui affiche "Analytics: " + message. Publiez les evenements "UserConnecte" et "AchatEffectue".',
    E'// TODO: @FunctionalInterface SimpleObserver avec void onEvent(String message)\n\n// TODO: class EventBus\n// - private List<SimpleObserver> listeners = new ArrayList<>()\n// - void subscribe(SimpleObserver o) : ajoute a listeners\n// - void publish(String message) : appelle onEvent() sur chaque listener\n\nimport java.util.ArrayList;\nimport java.util.List;\n\npublic class Main {\n    public static void main(String[] args) {\n        EventBus bus = new EventBus();\n\n        bus.subscribe(msg -> System.out.println("Logger: " + msg));\n        bus.subscribe(msg -> System.out.println("Analytics: " + msg));\n\n        bus.publish("UserConnecte");\n        bus.publish("AchatEffectue");\n    }\n}',
    E'import java.util.ArrayList;\nimport java.util.List;\n\n@FunctionalInterface\ninterface SimpleObserver {\n    void onEvent(String message);\n}\n\nclass EventBus {\n    private List<SimpleObserver> listeners = new ArrayList<>();\n\n    public void subscribe(SimpleObserver o) {\n        listeners.add(o);\n    }\n\n    public void publish(String message) {\n        for (SimpleObserver l : listeners) {\n            l.onEvent(message);\n        }\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        EventBus bus = new EventBus();\n\n        bus.subscribe(msg -> System.out.println("Logger: " + msg));\n        bus.subscribe(msg -> System.out.println("Analytics: " + msg));\n\n        bus.publish("UserConnecte");\n        bus.publish("AchatEffectue");\n    }\n}',
    'output.contains("Logger: UserConnecte") && output.contains("Analytics: UserConnecte") && output.contains("Logger: AchatEffectue") && output.contains("Analytics: AchatEffectue")',
    '["@FunctionalInterface garantit que SimpleObserver n a qu une seule methode abstraite, ce qui permet d utiliser des lambdas comme msg -> System.out.println(...)", "EventBus.publish() parcourt listeners avec un for-each et appelle l.onEvent(message) sur chaque abonne", "Les deux lambdas sont independantes : chaque publish() les appelle toutes les deux dans l ordre d abonnement"]',
    30,
    1
FROM lessons l WHERE l.slug = 'observer-pattern';

-- =============================================
-- EXERCICE 2 : StockMarket Observer (MEDIUM)
-- =============================================

INSERT INTO exercises (lesson_id, title, difficulty, description, starter_code, solution_code, test_code, hints, xp_reward, order_index)
SELECT l.id,
    'StockMarket - Cours des Actions',
    'MEDIUM',
    'Implementez l interface StockObserver avec void onPriceChange(String symbol, double price). Implementez StockMarket (le sujet) avec addObserver(StockObserver o), removeObserver(StockObserver o), et updatePrice(String symbol, double price) qui notifie tous les observateurs. Creez deux observateurs concrets : PortfolioTracker affiche "[PORTFOLIO] symbol : price EUR" et PriceAlert affiche "[ALERTE] symbol depasse 100 EUR !" uniquement si price > 100. Abonnez les deux, mettez a jour JAVA a 95.0 puis 110.0, et mettez a jour PYTHON a 80.0.',
    E'// TODO: interface StockObserver\n// void onPriceChange(String symbol, double price)\n\n// TODO: class StockMarket\n// - List<StockObserver> observers\n// - addObserver(StockObserver o)\n// - removeObserver(StockObserver o)\n// - updatePrice(String symbol, double price) : notifie tous les observers\n\n// TODO: class PortfolioTracker implements StockObserver\n// onPriceChange -> "[PORTFOLIO] " + symbol + " : " + price + " EUR"\n\n// TODO: class PriceAlert implements StockObserver\n// onPriceChange -> si price > 100 : "[ALERTE] " + symbol + " depasse 100 EUR !"\n\nimport java.util.ArrayList;\nimport java.util.List;\n\npublic class Main {\n    public static void main(String[] args) {\n        StockMarket market = new StockMarket();\n        market.addObserver(new PortfolioTracker());\n        market.addObserver(new PriceAlert());\n\n        market.updatePrice("JAVA", 95.0);\n        market.updatePrice("JAVA", 110.0);\n        market.updatePrice("PYTHON", 80.0);\n    }\n}',
    E'import java.util.ArrayList;\nimport java.util.List;\n\ninterface StockObserver {\n    void onPriceChange(String symbol, double price);\n}\n\nclass StockMarket {\n    private List<StockObserver> observers = new ArrayList<>();\n\n    public void addObserver(StockObserver o) {\n        observers.add(o);\n    }\n\n    public void removeObserver(StockObserver o) {\n        observers.remove(o);\n    }\n\n    public void updatePrice(String symbol, double price) {\n        for (StockObserver o : new ArrayList<>(observers)) {\n            o.onPriceChange(symbol, price);\n        }\n    }\n}\n\nclass PortfolioTracker implements StockObserver {\n    public void onPriceChange(String symbol, double price) {\n        System.out.println("[PORTFOLIO] " + symbol + " : " + price + " EUR");\n    }\n}\n\nclass PriceAlert implements StockObserver {\n    public void onPriceChange(String symbol, double price) {\n        if (price > 100) {\n            System.out.println("[ALERTE] " + symbol + " depasse 100 EUR !");\n        }\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        StockMarket market = new StockMarket();\n        market.addObserver(new PortfolioTracker());\n        market.addObserver(new PriceAlert());\n\n        market.updatePrice("JAVA", 95.0);\n        market.updatePrice("JAVA", 110.0);\n        market.updatePrice("PYTHON", 80.0);\n    }\n}',
    'output.contains("[PORTFOLIO] JAVA : 95.0 EUR") && output.contains("[PORTFOLIO] JAVA : 110.0 EUR") && output.contains("[ALERTE] JAVA depasse 100 EUR !") && output.contains("[PORTFOLIO] PYTHON : 80.0 EUR") && !output.contains("[ALERTE] PYTHON")',
    '["StockMarket.updatePrice() parcourt une copie de la liste : for (StockObserver o : new ArrayList<>(observers)) pour eviter les ConcurrentModificationException", "PriceAlert ne doit afficher l alerte QUE si price > 100 : JAVA a 95.0 ne declenche pas d alerte, JAVA a 110.0 oui, PYTHON a 80.0 non", "PortfolioTracker affiche toujours le prix quelle que soit la valeur : 3 updatePrice = 3 lignes [PORTFOLIO]"]',
    40,
    2
FROM lessons l WHERE l.slug = 'observer-pattern';

-- =============================================
-- EXERCICE 3 : NewsAgency systeme complet (HARD)
-- =============================================

INSERT INTO exercises (lesson_id, title, difficulty, description, starter_code, solution_code, test_code, hints, xp_reward, order_index)
SELECT l.id,
    'NewsAgency - Agence de Presse',
    'HARD',
    'Implementez un systeme d agence de presse complet. Interface NewsObserver avec void onNews(String category, String headline). Classe NewsAgency (sujet) avec addObserver, removeObserver, publish(String category, String headline) qui notifie. Classe Subscriber avec un nom et une categorie preferee : onNews affiche "[nom] Lu: headline" UNIQUEMENT si category correspond a sa categorie. Classe BreakingNewsAlert : onNews affiche "[FLASH] headline" uniquement si category vaut "URGENT". Classe NewsLogger : enregistre toutes les news dans une List<String> avec "category|headline", getLog() retourne la liste. Publiez 3 actualites et affichez le log complet.',
    E'// TODO: interface NewsObserver\n// void onNews(String category, String headline)\n\n// TODO: class NewsAgency\n// - addObserver, removeObserver, publish(String category, String headline)\n\n// TODO: class Subscriber implements NewsObserver\n// - Subscriber(String name, String preferredCategory)\n// - onNews : affiche "[name] Lu: headline" si category.equals(preferredCategory)\n\n// TODO: class BreakingNewsAlert implements NewsObserver\n// - onNews : affiche "[FLASH] headline" si category.equals("URGENT")\n\n// TODO: class NewsLogger implements NewsObserver\n// - private List<String> log = new ArrayList<>()\n// - onNews : ajoute "category|headline" dans log\n// - List<String> getLog() : retourne log\n\nimport java.util.ArrayList;\nimport java.util.List;\n\npublic class Main {\n    public static void main(String[] args) {\n        NewsAgency agency = new NewsAgency();\n\n        Subscriber alice = new Subscriber("Alice", "SPORT");\n        Subscriber bob = new Subscriber("Bob", "TECH");\n        BreakingNewsAlert alert = new BreakingNewsAlert();\n        NewsLogger logger = new NewsLogger();\n\n        agency.addObserver(alice);\n        agency.addObserver(bob);\n        agency.addObserver(alert);\n        agency.addObserver(logger);\n\n        agency.publish("SPORT", "France remporte le tournoi");\n        agency.publish("URGENT", "Alerte meteorologique majeure");\n        agency.publish("TECH", "Nouveau langage de programmation sort");\n\n        System.out.println("--- Journal complet ---");\n        for (String entry : logger.getLog()) {\n            System.out.println(entry);\n        }\n    }\n}',
    E'import java.util.ArrayList;\nimport java.util.List;\n\ninterface NewsObserver {\n    void onNews(String category, String headline);\n}\n\nclass NewsAgency {\n    private List<NewsObserver> observers = new ArrayList<>();\n\n    public void addObserver(NewsObserver o) {\n        observers.add(o);\n    }\n\n    public void removeObserver(NewsObserver o) {\n        observers.remove(o);\n    }\n\n    public void publish(String category, String headline) {\n        for (NewsObserver o : new ArrayList<>(observers)) {\n            o.onNews(category, headline);\n        }\n    }\n}\n\nclass Subscriber implements NewsObserver {\n    private String name;\n    private String preferredCategory;\n\n    public Subscriber(String name, String preferredCategory) {\n        this.name = name;\n        this.preferredCategory = preferredCategory;\n    }\n\n    public void onNews(String category, String headline) {\n        if (category.equals(preferredCategory)) {\n            System.out.println("[" + name + "] Lu: " + headline);\n        }\n    }\n}\n\nclass BreakingNewsAlert implements NewsObserver {\n    public void onNews(String category, String headline) {\n        if (category.equals("URGENT")) {\n            System.out.println("[FLASH] " + headline);\n        }\n    }\n}\n\nclass NewsLogger implements NewsObserver {\n    private List<String> log = new ArrayList<>();\n\n    public void onNews(String category, String headline) {\n        log.add(category + "|" + headline);\n    }\n\n    public List<String> getLog() {\n        return log;\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        NewsAgency agency = new NewsAgency();\n\n        Subscriber alice = new Subscriber("Alice", "SPORT");\n        Subscriber bob = new Subscriber("Bob", "TECH");\n        BreakingNewsAlert alert = new BreakingNewsAlert();\n        NewsLogger logger = new NewsLogger();\n\n        agency.addObserver(alice);\n        agency.addObserver(bob);\n        agency.addObserver(alert);\n        agency.addObserver(logger);\n\n        agency.publish("SPORT", "France remporte le tournoi");\n        agency.publish("URGENT", "Alerte meteorologique majeure");\n        agency.publish("TECH", "Nouveau langage de programmation sort");\n\n        System.out.println("--- Journal complet ---");\n        for (String entry : logger.getLog()) {\n            System.out.println(entry);\n        }\n    }\n}',
    'output.contains("[Alice] Lu: France remporte le tournoi") && !output.contains("[Alice] Lu: Alerte") && output.contains("[FLASH] Alerte meteorologique majeure") && output.contains("[Bob] Lu: Nouveau langage de programmation sort") && output.contains("SPORT|France remporte le tournoi") && output.contains("URGENT|Alerte meteorologique majeure") && output.contains("TECH|Nouveau langage de programmation sort")',
    '["Subscriber.onNews() affiche uniquement si category.equals(preferredCategory) : Alice reagit a SPORT, Bob a TECH, ni l un ni l autre a URGENT", "BreakingNewsAlert.onNews() affiche uniquement si category.equals(\"URGENT\") : seule la 2eme publication declenche [FLASH]", "NewsLogger.onNews() enregistre TOUTES les news sans filtre : log.add(category + \"|\" + headline). getLog() retourne la liste pour l affichage final"]',
    50,
    3
FROM lessons l WHERE l.slug = 'observer-pattern';
