-- V9: Exercice - Analyseur de texte

-- =============================================
-- EXERCICE : Analyseur de texte
-- =============================================

INSERT INTO exercises (lesson_id, title, description, starter_code, solution_code, test_code, hints, difficulty, xp_reward, order_index)
SELECT l.id,
    'Analyseur de texte',
    E'CONTEXTE\n\nVous developpez un module d analyse pour une application d apprentissage des langues. Ce module doit extraire des statistiques d une phrase et la transformer.\n\nOBJECTIFS D APPRENTISSAGE\n- Utiliser les methodes essentielles de String\n- Parcourir une String avec charAt() et length()\n- Distinguer equals() de ==\n- Utiliser StringBuilder pour construire une chaine\n\nSPECIFICATIONS\n\nA partir de la phrase : "Java est un langage puissant"\n\n1. Affichez le nombre de caracteres (espaces inclus)\n2. Affichez le nombre de mots (les mots sont separes par des espaces)\n3. Affichez le nombre de voyelles (a, e, i, o, u - insensible a la casse)\n4. Affichez la phrase en majuscules\n5. Affichez la phrase inversee (les caracteres dans l ordre inverse)\n\nEXEMPLE DE SORTIE ATTENDUE :\n  Caracteres : 27\n  Mots : 5\n  Voyelles : 10\n  Majuscules : JAVA EST UN LANGAGE PUISSANT\n  Inversee : tnasiup egagnal nu tse avaJ\n\nQUESTIONS DE REFLEXION\n- Pourquoi utiliser StringBuilder pour inverser la phrase plutot que + dans une boucle ?\n- Quelle methode de String permet de compter les mots sans boucle ?\n- Comment rendre le comptage de voyelles insensible a la casse ?',
    E'public class Main {\n    public static void main(String[] args) {\n        String phrase = "Java est un langage puissant";\n\n        // 1. Nombre de caracteres\n        int nbCaracteres = 0; // a completer\n\n        // 2. Nombre de mots (separes par des espaces)\n        int nbMots = 0; // a completer\n\n        // 3. Nombre de voyelles (a, e, i, o, u)\n        int nbVoyelles = 0;\n        String voyelles = "aeioуAEIOU";\n        for (int i = 0; i < phrase.length(); i++) {\n            // a completer\n        }\n\n        // 4. Phrase en majuscules\n        String majuscules = ""; // a completer\n\n        // 5. Phrase inversee avec StringBuilder\n        StringBuilder sb = new StringBuilder();\n        // a completer\n        String inversee = sb.toString();\n\n        System.out.println("Caracteres : " + nbCaracteres);\n        System.out.println("Mots : " + nbMots);\n        System.out.println("Voyelles : " + nbVoyelles);\n        System.out.println("Majuscules : " + majuscules);\n        System.out.println("Inversee : " + inversee);\n    }\n}',
    E'public class Main {\n    public static void main(String[] args) {\n        String phrase = "Java est un langage puissant";\n\n        // 1. Nombre de caracteres\n        int nbCaracteres = phrase.length();\n\n        // 2. Nombre de mots\n        int nbMots = phrase.split(" ").length;\n\n        // 3. Nombre de voyelles\n        int nbVoyelles = 0;\n        String voyelles = "aeiouAEIOU";\n        for (int i = 0; i < phrase.length(); i++) {\n            if (voyelles.contains(String.valueOf(phrase.charAt(i)))) {\n                nbVoyelles++;\n            }\n        }\n\n        // 4. Phrase en majuscules\n        String majuscules = phrase.toUpperCase();\n\n        // 5. Phrase inversee\n        StringBuilder sb = new StringBuilder(phrase);\n        String inversee = sb.reverse().toString();\n\n        System.out.println("Caracteres : " + nbCaracteres);\n        System.out.println("Mots : " + nbMots);\n        System.out.println("Voyelles : " + nbVoyelles);\n        System.out.println("Majuscules : " + majuscules);\n        System.out.println("Inversee : " + inversee);\n    }\n}',
    'output.contains("Caracteres : 27") && output.contains("Mots : 5") && output.contains("Voyelles : 10") && output.contains("JAVA EST UN LANGAGE PUISSANT") && output.contains("tnasiup egagnal nu tse avaJ")',
    E'Indice 1 : Le nombre de caracteres est simplement phrase.length().\nIndice 2 : Pour les mots, utilisez phrase.split(" ").length pour decouper par les espaces et compter les morceaux.\nIndice 3 : Pour les voyelles, a chaque iteration recuperez le caractere avec phrase.charAt(i), convertissez-le en String avec String.valueOf(), puis testez si voyelles.contains() le trouve.\nIndice 4 : Pour inverser, passez la phrase directement au constructeur de StringBuilder : new StringBuilder(phrase), puis appelez .reverse().toString().',
    'MEDIUM', 150, 1
FROM lessons l WHERE l.slug = 'strings';
